/**
 * ENTRENADORES
*/

INSERT INTO ENTRENADOR VALUES (1,"Azul");
INSERT INTO ENTRENADOR VALUES (2,"Lorelei");
INSERT INTO ENTRENADOR VALUES (3,"Bruno");
INSERT INTO ENTRENADOR VALUES (4,"Agatha");
INSERT INTO ENTRENADOR VALUES (5,"Lance");
INSERT INTO ENTRENADOR VALUES (6,"Brock");
INSERT INTO ENTRENADOR VALUES (7,"Mysty");
INSERT INTO ENTRENADOR VALUES (8,"Lt. Surge");
INSERT INTO ENTRENADOR VALUES (9,"Erika");
INSERT INTO ENTRENADOR VALUES (10,"Koga");
INSERT INTO ENTRENADOR VALUES (11,"Sabrina");
INSERT INTO ENTRENADOR VALUES (12,"Blaine");
INSERT INTO ENTRENADOR VALUES (13,"Giovanni");
INSERT INTO ENTRENADOR VALUES (14,"Atlas");
INSERT INTO ENTRENADOR VALUES (15,"Proton");
INSERT INTO ENTRENADOR VALUES (16,"Atenea");
INSERT INTO ENTRENADOR VALUES (17,"Petrel");
INSERT INTO ENTRENADOR VALUES (18,"Jessie");
INSERT INTO ENTRENADOR VALUES (19,"James");
INSERT INTO ENTRENADOR VALUES (20,"Admin Ruben");
INSERT INTO ENTRENADOR VALUES (21,"Admin Jose Manuel");
INSERT INTO ENTRENADOR VALUES (22,"Andres");
INSERT INTO ENTRENADOR VALUES (23,"Yessica");
INSERT INTO ENTRENADOR VALUES (24,"Danielle");
INSERT INTO ENTRENADOR VALUES (25,"Ruben");
INSERT INTO ENTRENADOR VALUES (26,"Ridel");
INSERT INTO ENTRENADOR VALUES (27,"Cristian");
INSERT INTO ENTRENADOR VALUES (28,"Alejandro");
INSERT INTO ENTRENADOR VALUES (29,"Gersan");
INSERT INTO ENTRENADOR VALUES (30,"Oak");

/**
 * VILLANOS
*/

INSERT INTO VILLANO VALUES (13,"Dominar el universo usando a todos los Pokemon");
INSERT INTO VILLANO VALUES (14,"Conseguir las comunicaciones de Johto");
INSERT INTO VILLANO VALUES (14,"Quitarle las colas a los Slowpoke y venderlas");
INSERT INTO VILLANO VALUES (14,"Ejecutiva del Team Rocket");
INSERT INTO VILLANO VALUES (14,"Infiltrarse en las organizaciones enemigas");
INSERT INTO VILLANO VALUES (14,"Conseguir pokemons para el Team Rocket");
INSERT INTO VILLANO VALUES (14,"Conseguir pokemons para el Team Rocket");

/**
 * LIDERES DE GIMNASIO
*/

INSERT INTO LIDER_GIMNASIO VALUES (2,1);
INSERT INTO LIDER_GIMNASIO VALUES (3,2);
INSERT INTO LIDER_GIMNASIO VALUES (4,3);
INSERT INTO LIDER_GIMNASIO VALUES (5,4);
INSERT INTO LIDER_GIMNASIO VALUES (6,5);
INSERT INTO LIDER_GIMNASIO VALUES (7,6);
INSERT INTO LIDER_GIMNASIO VALUES (8,7);
INSERT INTO LIDER_GIMNASIO VALUES (9,8);

/**
 * ENTRENADORES CASUALES
*/

INSERT INTO ENTRENADOR VALUES (20,8);
INSERT INTO ENTRENADOR VALUES (21,8);
INSERT INTO ENTRENADOR VALUES (22,7);
INSERT INTO ENTRENADOR VALUES (23,5);
INSERT INTO ENTRENADOR VALUES (24,3);
INSERT INTO ENTRENADOR VALUES (25,7);
INSERT INTO ENTRENADOR VALUES (26,6);
INSERT INTO ENTRENADOR VALUES (27,6);
INSERT INTO ENTRENADOR VALUES (28,5);
INSERT INTO ENTRENADOR VALUES (29,5);
INSERT INTO ENTRENADOR VALUES (30,8);

/**
 * CAMPEON DE LA LIGA
*/

INSERT INTO CAMPEON_LIGA VALUES (1,"Johto");

/**
 * ALTO MANDO
*/

INSERT INTO ALTO_MANDO VALUES (2,"Hielo");
INSERT INTO ALTO_MANDO VALUES (3,"Lucha");
INSERT INTO ALTO_MANDO VALUES (4,"Veneno");
INSERT INTO ALTO_MANDO VALUES (5,"Dragon");

/**
 * TIENE
*/

INSERT INTO TIENE VALUES (1,18,1);
INSERT INTO TIENE VALUES (1,65,1);
INSERT INTO TIENE VALUES (1,112,1);
INSERT INTO TIENE VALUES (1,103,1);
INSERT INTO TIENE VALUES (1,130,1);
INSERT INTO TIENE VALUES (1,6,1);

INSERT INTO TIENE VALUES (2,87,1);
INSERT INTO TIENE VALUES (2,91,1);
INSERT INTO TIENE VALUES (2,80,1);
INSERT INTO TIENE VALUES (2,124,1);
INSERT INTO TIENE VALUES (2,131,1);

INSERT INTO TIENE VALUES (3,95,2);
INSERT INTO TIENE VALUES (3,107,1);
INSERT INTO TIENE VALUES (3,106,1);
INSERT INTO TIENE VALUES (3,68,1);

INSERT INTO TIENE VALUES (4,94,2);
INSERT INTO TIENE VALUES (4,42,1);
INSERT INTO TIENE VALUES (4,93,1);
INSERT INTO TIENE VALUES (4,24,1);

INSERT INTO TIENE VALUES (5,149,1);
INSERT INTO TIENE VALUES (5,148,2);
INSERT INTO TIENE VALUES (5,130,1);
INSERT INTO TIENE VALUES (5,142,1);