/**
 * Script de insercion de datos
*/

/**
 * ESTADISTICAS BASE
*/

/**
 * CARACTERISTICAS
*/

INSERT INTO CARACTERISTICAS VALUES(1,6.9,0.7,"Semilla","Espesura","Starter");
INSERT INTO CARACTERISTICAS VALUES(2,13.0,1.0,"Semilla","Espesura","Normal");
INSERT INTO CARACTERISTICAS VALUES(3,100.0,2.0,"Semilla","Espesura","Normal");
INSERT INTO CARACTERISTICAS VALUES(4,8.5,0.6,"Lagartija","Mar llamas","Starter");
INSERT INTO CARACTERISTICAS VALUES(5,19,1.1,"Llama","Mar llamas","Normal");
INSERT INTO CARACTERISTICAS VALUES(6,90.5,1.5,"Llama","Mar llamas","Normal");
INSERT INTO CARACTERISTICAS VALUES(7,9.0,0.5,"Tortuguita","Torrente","Starter");
INSERT INTO CARACTERISTICAS VALUES(8,22.5,1.0,"Tortuga","Torrente","Normal");
INSERT INTO CARACTERISTICAS VALUES(9,85.5,1.6,"Marisco","Torrente","Normal");
INSERT INTO CARACTERISTICAS VALUES(10,2.9,0.3,"Gusano","Polvo escudo","Normal");
INSERT INTO CARACTERISTICAS VALUES(11,9.9,0.7,"Capullo","Mudar","Normal");
INSERT INTO CARACTERISTICAS VALUES(12,32,1.1,"Mariposa","Ojo compuesto","Normal");
INSERT INTO CARACTERISTICAS VALUES(13,3.2,0.3,"Oruga","Polvo escudo","Normal");
INSERT INTO CARACTERISTICAS VALUES(14,10.0,0.6,"Capullo","Mudar","Normal");
INSERT INTO CARACTERISTICAS VALUES(15,29.5,1.0,"Abeja venenosa","Enjambre","Normal");
INSERT INTO CARACTERISTICAS VALUES(16,1.8,0.3,"Pajarito","Vista lince","Normal");
INSERT INTO CARACTERISTICAS VALUES(17,30.0,1.1,"Pájaro","Vista lince","Normal");
INSERT INTO CARACTERISTICAS VALUES(18,39.5,1.5,"Pájaro","Vista lince","Normal");
INSERT INTO CARACTERISTICAS VALUES(19,3.5,0.3,"Ratón","Fuga","Normal");
INSERT INTO CARACTERISTICAS VALUES(20,18.5,0.7,"Ratón","Fuga","Normal");
INSERT INTO CARACTERISTICAS VALUES(21,38.0,1.2,"Pico","Vista lince","Normal");
INSERT INTO CARACTERISTICAS VALUES(22,6.9,2.0,"Serpiente","Intimidación","Normal");
INSERT INTO CARACTERISTICAS VALUES(23,85.0,3.5,"Cobra","Intimidación","Normal");
INSERT INTO CARACTERISTICAS VALUES(24,6.0,0.4,"Ratón","Electricidad estática","Normal");
INSERT INTO CARACTERISTICAS VALUES(25,30. ,0.8,"Ratón","Electricidad estática","Normal");
INSERT INTO CARACTERISTICAS VALUES(26,12.0,0.6,"Ratón","Velo arena","Normal");
INSERT INTO CARACTERISTICAS VALUES(27,7.0,0.4,"Pin veneno","Punto tóxico","Normal");
INSERT INTO CARACTERISTICAS VALUES(28,20.0,0.8,"Pin veneno","Punto tóxico","Normal");
INSERT INTO CARACTERISTICAS VALUES(29,60.0,1.3,"Taladro","Punto tóxico","Normal");
INSERT INTO CARACTERISTICAS VALUES(30,9.0,0.5,"Pin veneno","Punto tóxico","Normal");
INSERT INTO CARACTERISTICAS VALUES(31,19.5 ,0.9,"Pin veneno","Punto tóxico","Normal");
INSERT INTO CARACTERISTICAS VALUES(32,62.0,1.4,"Taladro","Punto tóxico","Normal");
INSERT INTO CARACTERISTICAS VALUES(33,7.5 ,0.6,"Hada","Gran encanto","Normal");
INSERT INTO CARACTERISTICAS VALUES(34,40.0,1.3,"Hada","Gran encanto","Normal");
INSERT INTO CARACTERISTICAS VALUES(35,9.9 ,0.6,"Zorro","Absorbe fuego","Normal");
INSERT INTO CARACTERISTICAS VALUES(36,19.9 ,1.1,"Zorro","Absorbe fuego","Normal");
INSERT INTO CARACTERISTICAS VALUES(37,5.5 ,0.5,"Globo","Gran encanto","Normal");
INSERT INTO CARACTERISTICAS VALUES(38,12.0,1.0,"Globo","Gran encanto","Normal");
INSERT INTO CARACTERISTICAS VALUES(39,7.5 ,0.8,"Murciélago","Foco interno","Normal");
INSERT INTO CARACTERISTICAS VALUES(40,55.0,1.6,"Murciélago","Foco interno","Normal");
INSERT INTO CARACTERISTICAS VALUES(41,5.4 ,0.5,"Hierbajo","Clorofila","Normal");
INSERT INTO CARACTERISTICAS VALUES(42,8.6 ,0.8,"Hierbajo","Clorofila","Normal");
INSERT INTO CARACTERISTICAS VALUES(43,18.2 ,1.2,"Flor","Clorofila","Normal");
INSERT INTO CARACTERISTICAS VALUES(44,5.4 ,0.3,"Hongo","Efect. espora","Normal");
INSERT INTO CARACTERISTICAS VALUES(45,29.5 ,1.0,"Hongo","Efect. espora","Normal");
INSERT INTO CARACTERISTICAS VALUES(46,30.0,1.0,"Insecto","Ojocompuesto","Normal");
INSERT INTO CARACTERISTICAS VALUES(47,12.5 ,1.5,"Polilla venenosa","Polvo escudo","Normal");
INSERT INTO CARACTERISTICAS VALUES(48,0.8 ,0.2,"Topo","Velo arena","Normal");
INSERT INTO CARACTERISTICAS VALUES(49,33.3,0.7,"Topo","Velo arena","Normal");
INSERT INTO CARACTERISTICAS VALUES(50,4.2 ,0.4,"Gato araña","Recogida","Normal");
INSERT INTO CARACTERISTICAS VALUES(51,2.0,0.3,"Pajarito","Vista lince","Normal");
INSERT INTO CARACTERISTICAS VALUES(52,2.0,0.3,"Pajarito","Vista lince","Normal");
INSERT INTO CARACTERISTICAS VALUES(53,2.0,0.3,"Pajarito","Vista lince","Normal");
INSERT INTO CARACTERISTICAS VALUES(54,2.0,0.3,"Pajarito","Vista lince","Normal");
INSERT INTO CARACTERISTICAS VALUES(55,2.0,0.3,"Pajarito","Vista lince","Normal");
INSERT INTO CARACTERISTICAS VALUES(56,2.0,0.3,"Pajarito","Vista lince","Normal");
INSERT INTO CARACTERISTICAS VALUES(57,2.0,0.3,"Pajarito","Vista lince","Normal");
INSERT INTO CARACTERISTICAS VALUES(58,2.0,0.3,"Pajarito","Vista lince","Normal");
INSERT INTO CARACTERISTICAS VALUES(59,2.0,0.3,"Pajarito","Vista lince","Normal");
INSERT INTO CARACTERISTICAS VALUES(60,2.0,0.3,"Pajarito","Vista lince","Normal");
INSERT INTO CARACTERISTICAS VALUES(61,2.0,0.3,"Pajarito","Vista lince","Normal");
INSERT INTO CARACTERISTICAS VALUES(62,2.0,0.3,"Pajarito","Vista lince","Normal");
INSERT INTO CARACTERISTICAS VALUES(63,2.0,0.3,"Pajarito","Vista lince","Normal");
INSERT INTO CARACTERISTICAS VALUES(64,2.0,0.3,"Pajarito","Vista lince","Normal");
INSERT INTO CARACTERISTICAS VALUES(65,2.0,0.3,"Pajarito","Vista lince","Normal");
INSERT INTO CARACTERISTICAS VALUES(66,2.0,0.3,"Pajarito","Vista lince","Normal");
INSERT INTO CARACTERISTICAS VALUES(67,2.0,0.3,"Pajarito","Vista lince","Normal");
INSERT INTO CARACTERISTICAS VALUES(68,2.0,0.3,"Pajarito","Vista lince","Normal");
INSERT INTO CARACTERISTICAS VALUES(69,2.0,0.3,"Pajarito","Vista lince","Normal");
INSERT INTO CARACTERISTICAS VALUES(70,2.0,0.3,"Pajarito","Vista lince","Normal");
INSERT INTO CARACTERISTICAS VALUES(71,2.0,0.3,"Pajarito","Vista lince","Normal");
INSERT INTO CARACTERISTICAS VALUES(72,2.0,0.3,"Pajarito","Vista lince","Normal");
INSERT INTO CARACTERISTICAS VALUES(73,2.0,0.3,"Pajarito","Vista lince","Normal");
INSERT INTO CARACTERISTICAS VALUES(74,2.0,0.3,"Pajarito","Vista lince","Normal");
INSERT INTO CARACTERISTICAS VALUES(75,2.0,0.3,"Pajarito","Vista lince","Normal");
INSERT INTO CARACTERISTICAS VALUES(76,2.0,0.3,"Pajarito","Vista lince","Normal");
INSERT INTO CARACTERISTICAS VALUES(78,2.0,0.3,"Pajarito","Vista lince","Normal");
INSERT INTO CARACTERISTICAS VALUES(79,2.0,0.3,"Pajarito","Vista lince","Normal");
INSERT INTO CARACTERISTICAS VALUES(80,2.0,0.3,"Pajarito","Vista lince","Normal");
INSERT INTO CARACTERISTICAS VALUES(81,2.0,0.3,"Pajarito","Vista lince","Normal");
INSERT INTO CARACTERISTICAS VALUES(82,2.0,0.3,"Pajarito","Vista lince","Normal");
INSERT INTO CARACTERISTICAS VALUES(83,2.0,0.3,"Pajarito","Vista lince","Normal");
INSERT INTO CARACTERISTICAS VALUES(84,2.0,0.3,"Pajarito","Vista lince","Normal");
INSERT INTO CARACTERISTICAS VALUES(85,2.0,0.3,"Pajarito","Vista lince","Normal");
INSERT INTO CARACTERISTICAS VALUES(86,2.0,0.3,"Pajarito","Vista lince","Normal");
INSERT INTO CARACTERISTICAS VALUES(87,2.0,0.3,"Pajarito","Vista lince","Normal");
INSERT INTO CARACTERISTICAS VALUES(88,2.0,0.3,"Pajarito","Vista lince","Normal");
INSERT INTO CARACTERISTICAS VALUES(89,2.0,0.3,"Pajarito","Vista lince","Normal");
INSERT INTO CARACTERISTICAS VALUES(90,2.0,0.3,"Pajarito","Vista lince","Normal");
INSERT INTO CARACTERISTICAS VALUES(91,2.0,0.3,"Pajarito","Vista lince","Normal");
INSERT INTO CARACTERISTICAS VALUES(92,2.0,0.3,"Pajarito","Vista lince","Normal");
INSERT INTO CARACTERISTICAS VALUES(93,2.0,0.3,"Pajarito","Vista lince","Normal");
INSERT INTO CARACTERISTICAS VALUES(94,2.0,0.3,"Pajarito","Vista lince","Normal");
INSERT INTO CARACTERISTICAS VALUES(95,2.0,0.3,"Pajarito","Vista lince","Normal");
INSERT INTO CARACTERISTICAS VALUES(96,2.0,0.3,"Pajarito","Vista lince","Normal");
INSERT INTO CARACTERISTICAS VALUES(97,2.0,0.3,"Pajarito","Vista lince","Normal");
INSERT INTO CARACTERISTICAS VALUES(98,2.0,0.3,"Pajarito","Vista lince","Normal");
INSERT INTO CARACTERISTICAS VALUES(99,2.0,0.3,"Pajarito","Vista lince","Normal");
INSERT INTO CARACTERISTICAS VALUES(100,2.0,0.3,"Pajarito","Vista lince","Normal");
INSERT INTO CARACTERISTICAS VALUES(101,2.0,0.3,"Pajarito","Vista lince","Normal");
INSERT INTO CARACTERISTICAS VALUES(102,2.0,0.3,"Pajarito","Vista lince","Normal");
INSERT INTO CARACTERISTICAS VALUES(103,2.0,0.3,"Pajarito","Vista lince","Normal");
INSERT INTO CARACTERISTICAS VALUES(104,2.0,0.3,"Pajarito","Vista lince","Normal");
INSERT INTO CARACTERISTICAS VALUES(105,2.0,0.3,"Pajarito","Vista lince","Normal");
INSERT INTO CARACTERISTICAS VALUES(106,2.0,0.3,"Pajarito","Vista lince","Normal");
INSERT INTO CARACTERISTICAS VALUES(107,2.0,0.3,"Pajarito","Vista lince","Normal");
INSERT INTO CARACTERISTICAS VALUES(108,2.0,0.3,"Pajarito","Vista lince","Normal");
INSERT INTO CARACTERISTICAS VALUES(109,2.0,0.3,"Pajarito","Vista lince","Normal");
INSERT INTO CARACTERISTICAS VALUES(110,2.0,0.3,"Pajarito","Vista lince","Normal");
INSERT INTO CARACTERISTICAS VALUES(111,2.0,0.3,"Pajarito","Vista lince","Normal");
INSERT INTO CARACTERISTICAS VALUES(112,2.0,0.3,"Pajarito","Vista lince","Normal");
INSERT INTO CARACTERISTICAS VALUES(113,2.0,0.3,"Pajarito","Vista lince","Normal");
INSERT INTO CARACTERISTICAS VALUES(114,2.0,0.3,"Pajarito","Vista lince","Normal");
INSERT INTO CARACTERISTICAS VALUES(115,2.0,0.3,"Pajarito","Vista lince","Normal");
INSERT INTO CARACTERISTICAS VALUES(116,2.0,0.3,"Pajarito","Vista lince","Normal");
INSERT INTO CARACTERISTICAS VALUES(117,2.0,0.3,"Pajarito","Vista lince","Normal");
INSERT INTO CARACTERISTICAS VALUES(118,2.0,0.3,"Pajarito","Vista lince","Normal");
INSERT INTO CARACTERISTICAS VALUES(119,2.0,0.3,"Pajarito","Vista lince","Normal");
INSERT INTO CARACTERISTICAS VALUES(120,2.0,0.3,"Pajarito","Vista lince","Normal");
INSERT INTO CARACTERISTICAS VALUES(121,2.0,0.3,"Pajarito","Vista lince","Normal");
INSERT INTO CARACTERISTICAS VALUES(122,2.0,0.3,"Pajarito","Vista lince","Normal");
INSERT INTO CARACTERISTICAS VALUES(123,2.0,0.3,"Pajarito","Vista lince","Normal");
INSERT INTO CARACTERISTICAS VALUES(124,2.0,0.3,"Pajarito","Vista lince","Normal");
INSERT INTO CARACTERISTICAS VALUES(125,2.0,0.3,"Pajarito","Vista lince","Normal");
INSERT INTO CARACTERISTICAS VALUES(126,2.0,0.3,"Pajarito","Vista lince","Normal");
INSERT INTO CARACTERISTICAS VALUES(127,2.0,0.3,"Pajarito","Vista lince","Normal");
INSERT INTO CARACTERISTICAS VALUES(128,2.0,0.3,"Pajarito","Vista lince","Normal");
INSERT INTO CARACTERISTICAS VALUES(129,2.0,0.3,"Pajarito","Vista lince","Normal");
INSERT INTO CARACTERISTICAS VALUES(130,2.0,0.3,"Pajarito","Vista lince","Normal");
INSERT INTO CARACTERISTICAS VALUES(131,2.0,0.3,"Pajarito","Vista lince","Normal");
INSERT INTO CARACTERISTICAS VALUES(132,2.0,0.3,"Pajarito","Vista lince","Normal");
INSERT INTO CARACTERISTICAS VALUES(133,2.0,0.3,"Pajarito","Vista lince","Normal");
INSERT INTO CARACTERISTICAS VALUES(134,2.0,0.3,"Pajarito","Vista lince","Normal");
INSERT INTO CARACTERISTICAS VALUES(135,2.0,0.3,"Pajarito","Vista lince","Normal");
INSERT INTO CARACTERISTICAS VALUES(136,2.0,0.3,"Pajarito","Vista lince","Normal");
INSERT INTO CARACTERISTICAS VALUES(137,2.0,0.3,"Pajarito","Vista lince","Normal");
INSERT INTO CARACTERISTICAS VALUES(138,2.0,0.3,"Pajarito","Vista lince","Normal");
INSERT INTO CARACTERISTICAS VALUES(139,2.0,0.3,"Pajarito","Vista lince","Normal");
INSERT INTO CARACTERISTICAS VALUES(140,2.0,0.3,"Pajarito","Vista lince","Normal");
INSERT INTO CARACTERISTICAS VALUES(141,2.0,0.3,"Pajarito","Vista lince","Normal");
INSERT INTO CARACTERISTICAS VALUES(142,2.0,0.3,"Pajarito","Vista lince","Normal");
INSERT INTO CARACTERISTICAS VALUES(143,2.0,0.3,"Pajarito","Vista lince","Normal");
INSERT INTO CARACTERISTICAS VALUES(144,2.0,0.3,"Pajarito","Vista lince","Normal");
INSERT INTO CARACTERISTICAS VALUES(145,2.0,0.3,"Pajarito","Vista lince","Normal");
INSERT INTO CARACTERISTICAS VALUES(146,2.0,0.3,"Pajarito","Vista lince","Normal");
INSERT INTO CARACTERISTICAS VALUES(147,2.0,0.3,"Pajarito","Vista lince","Normal");
INSERT INTO CARACTERISTICAS VALUES(148,2.0,0.3,"Pajarito","Vista lince","Normal");
INSERT INTO CARACTERISTICAS VALUES(149,2.0,0.3,"Pajarito","Vista lince","Normal");
INSERT INTO CARACTERISTICAS VALUES(150,2.0,0.3,"Pajarito","Vista lince","Normal");
INSERT INTO CARACTERISTICAS VALUES(151,2.0,0.3,"Pajarito","Vista lince","Normal");

/**
 * POKEMONS
*/

INSERT INTO POKEMON VALUES(1,"Bulbasaur","Planta","Veneno",1,1);
INSERT INTO POKEMON VALUES(2,"Ivysaur","Planta","Veneno",2,2);
INSERT INTO POKEMON VALUES(3,"Venusaur","Planta","Veneno",3,3);
INSERT INTO POKEMON VALUES(4,"Chamander","Fuego",NULL,4,4);
INSERT INTO POKEMON VALUES(5,"Charmelon","Fuego",NULL,5,5);
INSERT INTO POKEMON VALUES(6,"Charizard","Fuego","Pajaro",6,6);
INSERT INTO POKEMON VALUES(7,"Squirtle","Agua",NULL,7,7);
INSERT INTO POKEMON VALUES(8,"Wartortle","Agua",NULL,8,8);
INSERT INTO POKEMON VALUES(9,"Blastoise","Agua",NULL,9,9);
INSERT INTO POKEMON VALUES(10,"Caterpie","Bicho",NULL,10,10);
INSERT INTO POKEMON VALUES(11,"Metapod","Bicho",NULL,11,11);
INSERT INTO POKEMON VALUES(12,"Butterfree","Bicho","Pajaro",12,12);
INSERT INTO POKEMON VALUES(13,"Weedle","Bicho","Veneno",13,13);
INSERT INTO POKEMON VALUES(14,"Kakuna","Bicho","Veneno",14,14);
INSERT INTO POKEMON VALUES(15,"Beedrill","Bicho","Veneno",15,15);
INSERT INTO POKEMON VALUES(16,"Pidgey","Normal","Pajaro",16,16);
INSERT INTO POKEMON VALUES(17,"Pidgeotoo","Normal","Pajaro",17,17);
INSERT INTO POKEMON VALUES(18,"Pidgeot","Normal","Pajaro",18,18);
INSERT INTO POKEMON VALUES(19,"Rattata","Normal",NULL,19,19);
INSERT INTO POKEMON VALUES(20,"Raticate","Normal",NULL,20,20);
INSERT INTO POKEMON VALUES(21,"Spearwow","Normal","Pajaro",21,12);
INSERT INTO POKEMON VALUES(22,"Fearow","Normal","Pajaro",22,22);
INSERT INTO POKEMON VALUES(23,"Ekans","Veneno",NULL,23,23);
INSERT INTO POKEMON VALUES(24,"Arbok","Veneno",NULL,24,24);
INSERT INTO POKEMON VALUES(25,"Pikachu","Electrico",NULL,25,25);
INSERT INTO POKEMON VALUES(26,"Raichu","Electrico",NULL,26,26);
INSERT INTO POKEMON VALUES(27,"Sandshrew","Tierra",NULL,27,27);
INSERT INTO POKEMON VALUES(28,"Sandslash","Tierra",NULL,28,28);
INSERT INTO POKEMON VALUES(29,"Nidoran","Veneno",NULL,29,29);
INSERT INTO POKEMON VALUES(30,"Nidorina","Veneno",NULL,30,30);
INSERT INTO POKEMON VALUES(31,"Nidoqueen","Veneno","Tierra",31,31);
INSERT INTO POKEMON VALUES(32,"Nidoran","Veneno",NULL,32,32);
INSERT INTO POKEMON VALUES(33,"Nidorino","Veneno",NULL,33,33);
INSERT INTO POKEMON VALUES(34,"Nidoking","Veneno","Tierra",34,34);
INSERT INTO POKEMON VALUES(35,"Cleafairy","Normal",NULL,35,35);
INSERT INTO POKEMON VALUES(36,"Clefable","Normal",NULL,36,36);
INSERT INTO POKEMON VALUES(37,"Vulpix","Fuego",NULL,37,37);
INSERT INTO POKEMON VALUES(38,"Ninetales","Fuego",NULL,38,38);
INSERT INTO POKEMON VALUES(39,"Jigglypuff","Normal",NULL,39,39);
INSERT INTO POKEMON VALUES(40,"Wigglytuff","Normal",NULL,40,40);
INSERT INTO POKEMON VALUES(41,"Zubat","Veneno","Pajaro",41,41);
INSERT INTO POKEMON VALUES(42,"Golbat","Veneno","Pajaro",42,42);
INSERT INTO POKEMON VALUES(43,"Oddish","Planta","Veneno",43,43);
INSERT INTO POKEMON VALUES(44,"Gloom","Planta","Veneno",44,44);
INSERT INTO POKEMON VALUES(45,"Vileplume","Planta","Veneno",45,45);
INSERT INTO POKEMON VALUES(46,"Paras","Bicho","Planta",46,46);
INSERT INTO POKEMON VALUES(47,"Parasect","Bicho","Planta",47,47);
INSERT INTO POKEMON VALUES(48,"Vemonat","Bicho","Planta",48,48);
INSERT INTO POKEMON VALUES(49,"Venomoth","Bicho","Planta",49,49);
INSERT INTO POKEMON VALUES(50,"Diglett","Tierra",NULL,50,50);
INSERT INTO POKEMON VALUES(51,"Dugtrio","Tierra",NULL,51,51);
INSERT INTO POKEMON VALUES(52,"Meowth","Normal",NULL,52,52);
INSERT INTO POKEMON VALUES(53,"Persian","Normal",NULL,53,53);
INSERT INTO POKEMON VALUES(54,"Psduck","Agua",NULL,54,54);
INSERT INTO POKEMON VALUES(55,"Golduck","Agua",NULL,55,55);
INSERT INTO POKEMON VALUES(56,"Mankey","Lucha",NULL,56,56);
INSERT INTO POKEMON VALUES(57,"Primeape","Lucha",NULL,57,57);
INSERT INTO POKEMON VALUES(58,"Growlithe","Fuego",NULL,58,58);
INSERT INTO POKEMON VALUES(59,"Arcanine","Fuego",NULL,59,59);
INSERT INTO POKEMON VALUES(60,"Poliwag","Agua",NULL,60,60);
INSERT INTO POKEMON VALUES(61,"Poliwhirl","Agua",NULL,61,61);
INSERT INTO POKEMON VALUES(62,"Poliwrath","Agua","Lucha",62,62);
INSERT INTO POKEMON VALUES(63,"Abra","Psiquico",NULL,63,63);
INSERT INTO POKEMON VALUES(64,"Kadabra","Psiquico",NULL,64,64);
INSERT INTO POKEMON VALUES(65,"Alakazam","Psiquico",NULL,65,65);
INSERT INTO POKEMON VALUES(66,"Machop","Lucha",NULL,66,66);
INSERT INTO POKEMON VALUES(67,"Machoke","Lucha",NULL,67,67);
INSERT INTO POKEMON VALUES(68,"Machamp","Lucha",NULL,68,68);
INSERT INTO POKEMON VALUES(69,"Bellsprout","Planta","Veneno",69,69);
INSERT INTO POKEMON VALUES(70,"Weepinbell","Planta","Veneno",70,70);
INSERT INTO POKEMON VALUES(71,"Victreebel","Planta","Veneno",71,71);
INSERT INTO POKEMON VALUES(72,"Tentacool","Agua","Veneno",72,72);
INSERT INTO POKEMON VALUES(73,"Tentacruel","Agua","Veneno",73,73);
INSERT INTO POKEMON VALUES(74,"Geodude","Roca","Tierra",74,74);
INSERT INTO POKEMON VALUES(75,"Graveler","Roca","Tierra",75,75);
INSERT INTO POKEMON VALUES(76,"Golem","Roca","Tierra",76,76);
INSERT INTO POKEMON VALUES(77,"Ponyta","Fuego",NULL,77,77);
INSERT INTO POKEMON VALUES(78,"Rapidash","Fuego",NULL,78,78);
INSERT INTO POKEMON VALUES(79,"Slowpoke","Agua","Psiquico",79,79);
INSERT INTO POKEMON VALUES(80,"Slowbro","Agua","Psiquico",80,80);
INSERT INTO POKEMON VALUES(81,"Magnemite","Electrico",NULL,81,81);
INSERT INTO POKEMON VALUES(82,"Magneton","Electrico",NULL,82,82);
INSERT INTO POKEMON VALUES(83,"Farfetch d","Normal","Pajaro",83,83);
INSERT INTO POKEMON VALUES(84,"Doduo","Normal","Pajaro",84,84);  
INSERT INTO POKEMON VALUES(85,"Dodrio","Normal","Pajaro",85,85);
INSERT INTO POKEMON VALUES(86,"Seel","Agua",NULL,86,86);
INSERT INTO POKEMON VALUES(87,"Dewgong","Agua","Hielo",87,87);
INSERT INTO POKEMON VALUES(88,"Grimer","Veneno",NULL,88,88);
INSERT INTO POKEMON VALUES(89,"Muk","Veneno",NULL,89,89);
INSERT INTO POKEMON VALUES(90,"Shellder","Agua",NULL,90,90);
INSERT INTO POKEMON VALUES(91,"Cloyster","Agua","Hielo",91,91);
INSERT INTO POKEMON VALUES(92,"Gastly","Fastama","Veneno",92,92);
INSERT INTO POKEMON VALUES(93,"Haunter","Fastama","Veneno",93,93);
INSERT INTO POKEMON VALUES(94,"Gengar","Fastama","Veneno",94,94);
INSERT INTO POKEMON VALUES(95,"Onix","Roca","Tierra",95,95);
INSERT INTO POKEMON VALUES(96,"Drowzee","Psiquico",NULL,96,96);
INSERT INTO POKEMON VALUES(97,"Hypno","Psiquico",NULL,97,97);
INSERT INTO POKEMON VALUES(98,"Krabby","Agua",NULL,98,98);
INSERT INTO POKEMON VALUES(99,"Kingler","Agua",NULL,99,99);
INSERT INTO POKEMON VALUES(100,"Voltorb","Electrico",NULL,100,100);
INSERT INTO POKEMON VALUES(101,"Electrode","Electrico",NULL,101,101);
INSERT INTO POKEMON VALUES(102,"Exeggcute","Plata","Veneno",102,102);
INSERT INTO POKEMON VALUES(103,"Exaggutor","Plata","Veneno",103,103);
INSERT INTO POKEMON VALUES(104,"Cubone","Tierra",NULL,104,104);
INSERT INTO POKEMON VALUES(105,"Marwak","Tierra",NULL,105,105);
INSERT INTO POKEMON VALUES(106,"Hitmolle","Lucha",NULL,106,106);
INSERT INTO POKEMON VALUES(107,"Hitmochan","Lucha",NULL,107,107);
INSERT INTO POKEMON VALUES(108,"Lickitung","Normal",NULL,108,108);
INSERT INTO POKEMON VALUES(109,"Koffing","Veneno",NULL,109,109);
INSERT INTO POKEMON VALUES(110,"Weezing","Veneno",NULL,110,110);
INSERT INTO POKEMON VALUES(111,"Rhyhorn","Tierra","Roca",111,111);
INSERT INTO POKEMON VALUES(112,"Rhydon","Tierra","Roca",112,112);
INSERT INTO POKEMON VALUES(113,"Chansey","Normal",NULL,113,113);
INSERT INTO POKEMON VALUES(114,"Tangela","Planta",NULL,114,114);
INSERT INTO POKEMON VALUES(115,"Kangaskhan","Normal",NULL,115,115);
INSERT INTO POKEMON VALUES(116,"Horsea","Agua",NULL,116,116);
INSERT INTO POKEMON VALUES(117,"Seadra","Agua",NULL,117,117);
INSERT INTO POKEMON VALUES(118,"Goldeen","Agua",NULL,118,118);
INSERT INTO POKEMON VALUES(119,"Seaking","Agua",NULL,119,119);
INSERT INTO POKEMON VALUES(120,"Staryu","Agua",NULL,120,120);
INSERT INTO POKEMON VALUES(121,"Starmie","Agua","Psiquico",121,121);
INSERT INTO POKEMON VALUES(122,"Mr.Mime","Psiquico",NULL,122,122);
INSERT INTO POKEMON VALUES(123,"Scyther","Bicho","Pajaro",123,123);
INSERT INTO POKEMON VALUES(124,"Jynx","Hielo","Psiquico",124,124);
INSERT INTO POKEMON VALUES(125,"Electabuzz","Electrico",NULL,125,125);
INSERT INTO POKEMON VALUES(126,"Magmar","Fuego",NULL,126,126);
INSERT INTO POKEMON VALUES(127,"Pinsir","Bicho",NULL,127,127);
INSERT INTO POKEMON VALUES(128,"Tauros","Normal",NULL,128,128);
INSERT INTO POKEMON VALUES(129,"Magikarp","Agua",NULL,129,129);
INSERT INTO POKEMON VALUES(130,"Gyarados","Agua","Pajaro",130,130);
INSERT INTO POKEMON VALUES(131,"Lapras","Agua","Hielo",131,131);
INSERT INTO POKEMON VALUES(132,"Ditto","Normal",NULL,132,132);
INSERT INTO POKEMON VALUES(133,"Eevee","Normal",NULL,133,133);
INSERT INTO POKEMON VALUES(134,"Vaporeon","Agua",NULL,134,134);
INSERT INTO POKEMON VALUES(135,"Jolteon","Electrico",NULL,135,135);
INSERT INTO POKEMON VALUES(136,"Flareon","Fuego",NULL,136,136);
INSERT INTO POKEMON VALUES(137,"Porygon","Normal",NULL,137,137);
INSERT INTO POKEMON VALUES(138,"Omanyte","Roca","Agua",138,138);
INSERT INTO POKEMON VALUES(139,"Omastar","Roca","Agua",139,139);
INSERT INTO POKEMON VALUES(140,"Kabuto","Roca","Agua",140,140);
INSERT INTO POKEMON VALUES(141,"Kabutops","Roca","Agua",141,141);
INSERT INTO POKEMON VALUES(142,"Aerodactyl","Roca","Pajaro",142,142);
INSERT INTO POKEMON VALUES(143,"Snorlax","Normal",NULL,143,143);
INSERT INTO POKEMON VALUES(144,"Articuno","Hielo","Pajaro",144,144);
INSERT INTO POKEMON VALUES(145,"Zapdos","Electrico","Pajaro",145,145);
INSERT INTO POKEMON VALUES(146,"Moltres","Fuego","Pajaro",146,146);
INSERT INTO POKEMON VALUES(147,"Dratini","Dragon",NULL,147,147);
INSERT INTO POKEMON VALUES(148,"Dragonair","Dragon",NULL,148,148);
INSERT INTO POKEMON VALUES(149,"Dragonite","Dragon","Pajaro",149,149);
INSERT INTO POKEMON VALUES(150,"Mewtwo","Psiquico",NULL,150,150);
INSERT INTO POKEMON VALUES(151,"Mew","Psiquico",NULL,151,151);

/**
 * EVOLUCIONES
*/

INSERT INTO EVOLUCIONA VALUES(1,2,"Nivel");
INSERT INTO EVOLUCIONA VALUES(2,3,"Nivel");
INSERT INTO EVOLUCIONA VALUES(4,5,"Nivel");
INSERT INTO EVOLUCIONA VALUES(5,6,"Nivel");
INSERT INTO EVOLUCIONA VALUES(7,8,"Nivel");
INSERT INTO EVOLUCIONA VALUES(8,9,"Nivel");
INSERT INTO EVOLUCIONA VALUES(10,11,"Nivel");
INSERT INTO EVOLUCIONA VALUES(11,12,"Nivel");
INSERT INTO EVOLUCIONA VALUES(13,14,"Nivel");
INSERT INTO EVOLUCIONA VALUES(14,15,"Nivel");
INSERT INTO EVOLUCIONA VALUES(16,17,"Nivel");
INSERT INTO EVOLUCIONA VALUES(17,18,"Nivel");
INSERT INTO EVOLUCIONA VALUES(19,20,"Nivel");
INSERT INTO EVOLUCIONA VALUES(21,22,"Nivel");
INSERT INTO EVOLUCIONA VALUES(23,24,"Nivel");
INSERT INTO EVOLUCIONA VALUES(25,26,"Piedra");
INSERT INTO EVOLUCIONA VALUES(27,28,"Nivel");
INSERT INTO EVOLUCIONA VALUES(29,30,"Nivel");
INSERT INTO EVOLUCIONA VALUES(30,31,"Piedra");
INSERT INTO EVOLUCIONA VALUES(32,33,"Nivel");
INSERT INTO EVOLUCIONA VALUES(33,34,"Piedra");
INSERT INTO EVOLUCIONA VALUES(35,36,"Piedra");
INSERT INTO EVOLUCIONA VALUES(37,38,"Piedra");
INSERT INTO EVOLUCIONA VALUES(39,40,"Piedra");
INSERT INTO EVOLUCIONA VALUES(41,42,"Nivel");
INSERT INTO EVOLUCIONA VALUES(43,44,"Nivel");
INSERT INTO EVOLUCIONA VALUES(44,45,"Piedra");
INSERT INTO EVOLUCIONA VALUES(46,47,"Nivel");
INSERT INTO EVOLUCIONA VALUES(48,49,"Nivel");
INSERT INTO EVOLUCIONA VALUES(50,51,"Nivel");
INSERT INTO EVOLUCIONA VALUES(52,53,"Nivel");
INSERT INTO EVOLUCIONA VALUES(54,55,"Nivel");
INSERT INTO EVOLUCIONA VALUES(56,57,"Nivel");
INSERT INTO EVOLUCIONA VALUES(58,59,"Piedra");
INSERT INTO EVOLUCIONA VALUES(60,61,"Nivel");
INSERT INTO EVOLUCIONA VALUES(61,62,"Piedra");
INSERT INTO EVOLUCIONA VALUES(63,64,"Nivel");
INSERT INTO EVOLUCIONA VALUES(64,65,"Intercambio");
INSERT INTO EVOLUCIONA VALUES(66,67,"Nivel");
INSERT INTO EVOLUCIONA VALUES(67,68,"Intercambio");
INSERT INTO EVOLUCIONA VALUES(69,70,"Nivel");
INSERT INTO EVOLUCIONA VALUES(70,71,"Piedra");
INSERT INTO EVOLUCIONA VALUES(72,73,"Nivel");
INSERT INTO EVOLUCIONA VALUES(74,75,"Nivel");
INSERT INTO EVOLUCIONA VALUES(75,76,"Intercambio");
INSERT INTO EVOLUCIONA VALUES(77,78,"Nivel");
INSERT INTO EVOLUCIONA VALUES(79,80,"Nivel");
INSERT INTO EVOLUCIONA VALUES(81,82,"Nivel");
INSERT INTO EVOLUCIONA VALUES(84,85,"Nivel");
INSERT INTO EVOLUCIONA VALUES(86,87,"Nivel");
INSERT INTO EVOLUCIONA VALUES(88,89,"Nivel");
INSERT INTO EVOLUCIONA VALUES(90,91,"Piedra");
INSERT INTO EVOLUCIONA VALUES(92,93,"Nivel");
INSERT INTO EVOLUCIONA VALUES(93,94,"Intercambio");
INSERT INTO EVOLUCIONA VALUES(96,97,"Nivel");
INSERT INTO EVOLUCIONA VALUES(98,99,"Nivel");
INSERT INTO EVOLUCIONA VALUES(100,101,"Nivel");
INSERT INTO EVOLUCIONA VALUES(102,103,"Piedra");
INSERT INTO EVOLUCIONA VALUES(104,105,"Nivel");
INSERT INTO EVOLUCIONA VALUES(109,110,"Nivel");
INSERT INTO EVOLUCIONA VALUES(111,112,"Nivel");
INSERT INTO EVOLUCIONA VALUES(116,117,"Nivel");
INSERT INTO EVOLUCIONA VALUES(118,119,"Nivel");
INSERT INTO EVOLUCIONA VALUES(120,121,"Piedra");
INSERT INTO EVOLUCIONA VALUES(129,130,"Nivel");
INSERT INTO EVOLUCIONA VALUES(133,134,"Piedra");
INSERT INTO EVOLUCIONA VALUES(133,135,"Piedra");
INSERT INTO EVOLUCIONA VALUES(133,139,"Piedra");
INSERT INTO EVOLUCIONA VALUES(138,139,"Nivel");
INSERT INTO EVOLUCIONA VALUES(140,141,"Nivel");
INSERT INTO EVOLUCIONA VALUES(147,148,"Nivel");
INSERT INTO EVOLUCIONA VALUES(148,149,"Nivel");

/**
 * MOVIMIENTOS
*/

INSERT INTO MOVIMIENTO VALUES(1,"Burbuja","Agua","Especial",30,40,100,NULL); /* Agua */
INSERT INTO MOVIMIENTO VALUES(2,"Cascada","Agua","Fisico",15,80,100,NULL);
INSERT INTO MOVIMIENTO VALUES(3,"Hidrobomba","Agua","Espcial",5,110,80,NULL);
INSERT INTO MOVIMIENTO VALUES(4,"Martillazo","Agua","Fisico",10,100,90,NULL);
INSERT INTO MOVIMIENTO VALUES(5,"Pistola agua","Agua","Especial",25,40,100,NULL);
INSERT INTO MOVIMIENTO VALUES(6,"Rayo burbuja","Agua","Especial",20,65,100,NULL);
INSERT INTO MOVIMIENTO VALUES(7,"Refugio","Agua","Estado",40,0,100,NULL);
INSERT INTO MOVIMIENTO VALUES(8,"Surf","Agua","Especial",15,90,100,NULL);
INSERT INTO MOVIMIENTO VALUES(9,"Tenaza","Agua","Fisico",15,35,85,NULL);
INSERT INTO MOVIMIENTO VALUES(10,"Chupavidas","Bicho","Fisico",10,80,100,NULL); /* Bicho */
INSERT INTO MOVIMIENTO VALUES(11,"Disparo demora","Bicho","Estado",40,0,95,NULL);
INSERT INTO MOVIMIENTO VALUES(12,"Doble ataque","Bicho","Fisico",20,25,100,NULL);
INSERT INTO MOVIMIENTO VALUES(13,"Pin misil","Bicho","Fisico",20,25,95,NULL);
INSERT INTO MOVIMIENTO VALUES(14,"Furia dragon","Dragon","Especial",10,1,100,NULL); /* Dragon */
INSERT INTO MOVIMIENTO VALUES(15,"Impactrueno","Electrico","Especial",30,40,100,1); /* Electrico */ 
INSERT INTO MOVIMIENTO VALUES(16,"Onda trueno","Electrico","Estado",20,0,90,1);
INSERT INTO MOVIMIENTO VALUES(17,"Punio trueno","Electrico","Fisico",15,75,100,1);
INSERT INTO MOVIMIENTO VALUES(18,"Rayo","Electrico","Especial",15,90,100,1);
INSERT INTO MOVIMIENTO VALUES(19,"Trueno","Electrico","Especial",10,110,70,1);
INSERT INTO MOVIMIENTO VALUES(20,"Lenqüetazo","Fastama","Fisico",30,30,100,1); /* Fastama */
INSERT INTO MOVIMIENTO VALUES(21,"Rayo confuso","Fastama","Estado",10,0,100,6);
INSERT INTO MOVIMIENTO VALUES(22,"Tiniebla","Fastama","Especial",15,1,100,NULL);
INSERT INTO MOVIMIENTO VALUES(23,"Ascuas","Fuego","Especial",25,40,100,2); /* Fuego */
INSERT INTO MOVIMIENTO VALUES(24,"Giro fuego","Fuego","Especial",15,35,85,NULL);
INSERT INTO MOVIMIENTO VALUES(25,"Lanzallamas","Fuego","Especial",15,90,100,2);
INSERT INTO MOVIMIENTO VALUES(26,"Llamarada","Fuego","Especial",5,110,85,2);
INSERT INTO MOVIMIENTO VALUES(27,"Punio fuego","Fuego","Fisico",15,75,100,2);
INSERT INTO MOVIMIENTO VALUES(28,"Neblina","Hielo","Estado",30,0,100,NULL); /* Hielo */
INSERT INTO MOVIMIENTO VALUES(29,"Niebla","Hielo","Estado",30,0,100,NULL);
INSERT INTO MOVIMIENTO VALUES(30,"Punio hielo","Hielo","Fisico",15,75,100,5);
INSERT INTO MOVIMIENTO VALUES(31,"Rayo aurora","Hielo","Especial",20,65,100,NULL);
INSERT INTO MOVIMIENTO VALUES(32,"Rayo hielo","Hielo","Especial",10,90,100,5);
INSERT INTO MOVIMIENTO VALUES(33,"Vestisca","Hielo","Estado",5,110,70,5);
INSERT INTO MOVIMIENTO VALUES(34,"Contraataque","Lucha","Fisico",20,1,100,NULL); /* Lucha */
INSERT INTO MOVIMIENTO VALUES(35,"Doble patada","Lucha","Fisico",30,30,100,NULL);
INSERT INTO MOVIMIENTO VALUES(36,"Movimineto sismico","Lucha","Fisico",20,1,100,NULL);
INSERT INTO MOVIMIENTO VALUES(37,"Patada baja","Lucha","Fisico",20,1,100,NULL);
INSERT INTO MOVIMIENTO VALUES(38,"Patada giro","Lucha","Fisico",15,60,85,NULL);
INSERT INTO MOVIMIENTO VALUES(39,"Patada salto","Lucha","Fisico",10,100,95,NULL);
INSERT INTO MOVIMIENTO VALUES(40,"Patada salto alta","Lucha","Fisico",10,100,95,NULL);
INSERT INTO MOVIMIENTO VALUES(41,"Sumision","Lucha","Fisico",20,80,80,NULL);
INSERT INTO MOVIMIENTO VALUES(42,"Afilar","Normal","Estado",30,0,100,NULL); /* Normal */
INSERT INTO MOVIMIENTO VALUES(43,"Agarre","Normal","Fisico",30,55,100,NULL);
INSERT INTO MOVIMIENTO VALUES(44,"Amortiguador","Normal","Estado",10,0,100,NULL);
INSERT INTO MOVIMIENTO VALUES(45,"Anulacion","Normal","Estado",20,0,100,NULL);
INSERT INTO MOVIMIENTO VALUES(46,"Araniazo","Normal","Fisico",35,40,100,NULL);
INSERT INTO MOVIMIENTO VALUES(47,"Atadura","Normal","Fisico",20,15,85,10);
INSERT INTO MOVIMIENTO VALUES(48,"Ataque arena","Normal","Estado",15,0,100,NULL);
INSERT INTO MOVIMIENTO VALUES(49,"Ataque furia","Normal","Fisico",20,15,85,NULL);
INSERT INTO MOVIMIENTO VALUES(50,"Ataque rapido","Normal","Fisico",30,40,100,NULL);
INSERT INTO MOVIMIENTO VALUES(51,"Autodestruccion","Normal","Fisico",5,200,100,NULL);
INSERT INTO MOVIMIENTO VALUES(52,"Beso amoroso","Normal","Estado",10,0,75,NULL);
INSERT INTO MOVIMIENTO VALUES(53,"Bomba huevo","Normal","Fisico",10,100,75,NULL);
INSERT INTO MOVIMIENTO VALUES(54,"Bomba sonica","Normal","Especial",20,1,90,NULL);
INSERT INTO MOVIMIENTO VALUES(55,"Cabezazo","Normal","Fisico",10,130,100,NULL);
INSERT INTO MOVIMIENTO VALUES(56,"Canto","Normal","Estado",15,0,55,4);
INSERT INTO MOVIMIENTO VALUES(57,"Chirrido","Normal","Estado",40,0,85,NULL);
INSERT INTO MOVIMIENTO VALUES(58,"Clavo canion","Normal","Fisico",15,20,100,NULL);
INSERT INTO MOVIMIENTO VALUES(59,"Conversion","Normal","Estado",30,0,100,NULL);
INSERT INTO MOVIMIENTO VALUES(60,"Cornada","Normal","Fisico",25,65,100,NULL);
INSERT INTO MOVIMIENTO VALUES(61,"Corte","Normal","Fisico",30,50,95,NULL);
INSERT INTO MOVIMIENTO VALUES(62,"Cuchillada","Normal","Fisico",20,70,100,NULL);
INSERT INTO MOVIMIENTO VALUES(63,"Danza espada","Normal","Estado",20,0,100,NULL);
INSERT INTO MOVIMIENTO VALUES(64,"Derribo","Normal","Fisico",20,90,85,NULL);
INSERT INTO MOVIMIENTO VALUES(65,"Desarrollo","Normal","Estado",20,0,100,NULL);
INSERT INTO MOVIMIENTO VALUES(66,"Deslumbrar","Normal","Estado",30,0,100,NULL);
INSERT INTO MOVIMIENTO VALUES(67,"Destello","Normal","Estado",20,0,100,NULL);
INSERT INTO MOVIMIENTO VALUES(68,"Destructor","Normal","Fisico",35,40,100,NULL);
INSERT INTO MOVIMIENTO VALUES(69,"Dia de pago","Normal","Fisico",20,40,100,NULL);
INSERT INTO MOVIMIENTO VALUES(70,"Doble equipo","Normal","Estado",15,0,100,NULL);
INSERT INTO MOVIMIENTO VALUES(71,"Doble filo","Normal","Fisico",15,120,100,NULL);
INSERT INTO MOVIMIENTO VALUES(72,"Doblebofeton","Normal","Fisico",10,15,85,NULL);
INSERT INTO MOVIMIENTO VALUES(73,"Explosion","Normal","Fisico",5,250,100,NULL);
INSERT INTO MOVIMIENTO VALUES(74,"Foco energía","Normal","Estado",30,0,100,NULL);
INSERT INTO MOVIMIENTO VALUES(75,"Fortaleza","Normal","Estado",30,0,100,NULL);
INSERT INTO MOVIMIENTO VALUES(76,"Fuerza","Normal","Fisico",15,80,100,NULL);
INSERT INTO MOVIMIENTO VALUES(77,"Furia","Normal","Fisico",20,20,100,NULL);
INSERT INTO MOVIMIENTO VALUES(78,"Golpe","Normal","Fisico",10,120,100,NULL);
INSERT INTO MOVIMIENTO VALUES(79,"Golpe cabeza","Normal","Fisico",15,70,100,NULL);
INSERT INTO MOVIMIENTO VALUES(80,"Golpe cuerpo","Normal","Fisico",15,85,100,NULL);
INSERT INTO MOVIMIENTO VALUES(81,"Golpe karate","Normal","Fisico",25,50,100,1);
INSERT INTO MOVIMIENTO VALUES(82,"Golpes furia","Normal","Fisico",15,18,80,NULL);
INSERT INTO MOVIMIENTO VALUES(83,"Grunido","Normal","Estado",40,0,100,NULL);
INSERT INTO MOVIMIENTO VALUES(84,"Guillotina","Normal","Fisico",5,1,30,NULL);
INSERT INTO MOVIMIENTO VALUES(85,"Hipercolmillo","Normal","Fisico",15,80,90,NULL);
INSERT INTO MOVIMIENTO VALUES(86,"Hiperrayo","Normal","Especial",5,150,90,NULL);
INSERT INTO MOVIMIENTO VALUES(87,"Latigo","Normal","Estado",30,0,100,NULL);
INSERT INTO MOVIMIENTO VALUES(88,"Malicioso","Normal","Estado",30,0,100,NULL);
INSERT INTO MOVIMIENTO VALUES(89,"Megapatada","Normal","Fisico",5,120,75,NULL);
INSERT INTO MOVIMIENTO VALUES(90,"Megapunio","Normal","Fisico",20,80,85,NULL);
INSERT INTO MOVIMIENTO VALUES(91,"Metronomo","Normal","Estado",10,0,100,NULL);
INSERT INTO MOVIMIENTO VALUES(92,"Mimetico","Normal","Estado",10,0,100,NULL);
INSERT INTO MOVIMIENTO VALUES(93,"Mordisco","Normal","Fisico",25,60,100,NULL);
INSERT INTO MOVIMIENTO VALUES(94,"Pantalla de humo","Normal","Estado",20,0,100,NULL);
INSERT INTO MOVIMIENTO VALUES(95,"Perforador","Normal","Fisico",5,1,30,NULL);
INSERT INTO MOVIMIENTO VALUES(96,"Pisoton","Normal","Fisico",20,65,100,NULL);
INSERT INTO MOVIMIENTO VALUES(97,"Placaje","Normal","Fisico",35,40,100,NULL);
INSERT INTO MOVIMIENTO VALUES(98,"Atizar","Normal","Fisico",20,80,75,NULL);
INSERT INTO MOVIMIENTO VALUES(99,"Presa","Normal","Fisico",20,15,85,NULL);
INSERT INTO MOVIMIENTO VALUES(100,"Punio cometa","Normal","Fisico",15,85,85,NULL);
INSERT INTO MOVIMIENTO VALUES(101,"Punio mareo","Normal","Fisico",10,70,100,6);
INSERT INTO MOVIMIENTO VALUES(102,"Rapidez","Normal","Especial",20,60,100,NULL);
INSERT INTO MOVIMIENTO VALUES(103,"Recuperacion","Normal","Estado",10,0,100,NULL);
INSERT INTO MOVIMIENTO VALUES(104,"Reduccion","Normal","Estado",10,0,100,NULL);
INSERT INTO MOVIMIENTO VALUES(105,"Remolino","Normal","Estado",20,0,100,10);
INSERT INTO MOVIMIENTO VALUES(106,"Constriccion","Normal","Fisico",20,15,90,10);
INSERT INTO MOVIMIENTO VALUES(107,"Restriccion","Normal","Fisico",35,10,100,10);
INSERT INTO MOVIMIENTO VALUES(108,"Rizo defensa","Normal","Estado",40,0,100,NULL);
INSERT INTO MOVIMIENTO VALUES(109,"Rugido","Normal","Estado",20,0,100,NULL);
INSERT INTO MOVIMIENTO VALUES(110,"Salpicadura","Normal","Estado",40,0,100,NULL);
INSERT INTO MOVIMIENTO VALUES(111,"Superdiente","Normal","Fisico",10,1,90,NULL);
INSERT INTO MOVIMIENTO VALUES(112,"Supersonico","Normal","Estado",20,0,55,6);
INSERT INTO MOVIMIENTO VALUES(113,"Sustituto","Normal","Estado",10,0,100,NULL);
INSERT INTO MOVIMIENTO VALUES(114,"Tornado","Normal","Especial",35,40,100,NULL);
INSERT INTO MOVIMIENTO VALUES(115,"Transformacion","Normal","Estado",10,0,100,NULL);
INSERT INTO MOVIMIENTO VALUES(116,"Triataque","Normal","Especial",10,80,100,NULL);
INSERT INTO MOVIMIENTO VALUES(117,"Venganza","Normal","Fisico",10,1,100,NULL);
INSERT INTO MOVIMIENTO VALUES(118,"Viento cortante","Normal","Especial",10,80,100,NULL);
INSERT INTO MOVIMIENTO VALUES(119,"Absorber","Planta","Especial",25,20,100,8); /* Planta */
INSERT INTO MOVIMIENTO VALUES(120,"Danza petalo","Planta","Especial",10,120,100,NULL);
INSERT INTO MOVIMIENTO VALUES(121,"Drenadoras","Planta","Estado",10,0,90,8);
INSERT INTO MOVIMIENTO VALUES(122,"Espora","Planta","Estado",15,0,100,4);
INSERT INTO MOVIMIENTO VALUES(123,"Hoja afilada","Planta","Fisico",25,55,95,NULL);
INSERT INTO MOVIMIENTO VALUES(124,"Latigo cepa","Planta","Fisico",25,45,100,NULL);
INSERT INTO MOVIMIENTO VALUES(125,"Megaagotar","Planta","Especial",15,40,100,8);
INSERT INTO MOVIMIENTO VALUES(126,"Paralizador","Planta","Estado",30,0,75,1);
INSERT INTO MOVIMIENTO VALUES(127,"Rayo solar","Planta","Especial",10,120,100,NULL);
INSERT INTO MOVIMIENTO VALUES(128,"Somnifero","Planta","Estado",15,0,75,4);
INSERT INTO MOVIMIENTO VALUES(129,"Agilidad","Psiquico","Estado",30,0,100,NULL); /* Psiquico */
INSERT INTO MOVIMIENTO VALUES(130,"Amnesia","Psiquico","Estado",20,0,100,NULL);
INSERT INTO MOVIMIENTO VALUES(131,"Barrera","Psiquico","Especial",20,0,100,NULL);
INSERT INTO MOVIMIENTO VALUES(132,"Come suenios","Psiquico","Especial",15,100,100,NULL);
INSERT INTO MOVIMIENTO VALUES(133,"Confusion","Psiquico","Estado",25,50,100,NULL);
INSERT INTO MOVIMIENTO VALUES(134,"Descanso","Psiquico","Estado",10,0,100,4);
INSERT INTO MOVIMIENTO VALUES(135,"Hipnosis","Psiquico","Estado",20,0,60,4);
INSERT INTO MOVIMIENTO VALUES(136,"Kinetico","Psiquico","Estado",15,0,80,NULL);
INSERT INTO MOVIMIENTO VALUES(137,"Meditacion","Psiquico","Estado",40,0,100,NULL);
INSERT INTO MOVIMIENTO VALUES(138,"Pantalla de luz","Psiquico","Especial",30,0,100,NULL);
INSERT INTO MOVIMIENTO VALUES(139,"Psicoonda","Psiquico","Estado",5,140,90,NULL);
INSERT INTO MOVIMIENTO VALUES(140,"Psicorrayo","Psiquico","Especial",20,65,100,NULL);
INSERT INTO MOVIMIENTO VALUES(141,"Psiquico","Psiquico","Especial",10,90,100,NULL);
INSERT INTO MOVIMIENTO VALUES(142,"Reflejo","Psiquico","Estado",20,0,100,NULL);
INSERT INTO MOVIMIENTO VALUES(143,"Teletransporte","Psiquico","Estado",20,0,100,NULL);
INSERT INTO MOVIMIENTO VALUES(144,"Avalancha","Roca","Fisico",10,75,90,NULL); /* Roca */
INSERT INTO MOVIMIENTO VALUES(145,"Lanzarrocas","Roca","Fisico",15,50,90,NULL);
INSERT INTO MOVIMIENTO VALUES(146,"Excavar","Tierra","Fisico",10,80,100,NULL); /* Tierra */
INSERT INTO MOVIMIENTO VALUES(147,"Fisura","Tierra","Fisico",5,1,30,NULL);
INSERT INTO MOVIMIENTO VALUES(148,"Hueso palo","Tierra","Fisico",20,65,85,NULL);
INSERT INTO MOVIMIENTO VALUES(149,"Huesomerang","Tierra","Fisico",10,50,90,NULL);
INSERT INTO MOVIMIENTO VALUES(150,"Terremoto","Tierra","Fisico",10,100,10,NULL);
INSERT INTO MOVIMIENTO VALUES(151,"Armadura acida","Veneno","Estado",20,0,100,NULL); /* Veneno */
INSERT INTO MOVIMIENTO VALUES(152,"Gas venenoso","Veneno","Estado",40,0,90,3);
INSERT INTO MOVIMIENTO VALUES(153,"Picotazo venenoso","Veneno","Fisico",35,10,100,3);
INSERT INTO MOVIMIENTO VALUES(154,"Polucion","Veneno","Especial",20,20,70.3);
INSERT INTO MOVIMIENTO VALUES(155,"Polvo veneno","Veneno","Estado",35,0,75,3);
INSERT INTO MOVIMIENTO VALUES(156,"Residuos","Veneno","Especial",20,65,100,3);
INSERT INTO MOVIMIENTO VALUES(157,"Toxico","Veneno","Estado",10,0,90,3);
INSERT INTO MOVIMIENTO VALUES(158,"Acido","Veneno","Especial",30,40,100,NULL);
INSERT INTO MOVIMIENTO VALUES(159,"Ataque ala","Pajaro","Fisico",35,60,100,NULL); /* Pajaro */
INSERT INTO MOVIMIENTO VALUES(160,"Ataque aereo","Pajaro","Fisico",5,140,90,NULL);
INSERT INTO MOVIMIENTO VALUES(161,"Movimineto espejo","Pajaro","Estado",20,0,100,NULL);
INSERT INTO MOVIMIENTO VALUES(162,"Pico taladro","Pajaro","Fisico",20,80,100,NULL);
INSERT INTO MOVIMIENTO VALUES(163,"Picotazo","Pajaro","Fisico",35,35,100,NULL);
INSERT INTO MOVIMIENTO VALUES(164,"Vuelo","Pajaro","Fisico",15,90,95,NULL);

/**
 * CONOCE
*/

INSERT INTO CONOCE VALUES(1,119); /* Bulbasaur*/
INSERT INTO CONOCE VALUES(1,121);
INSERT INTO CONOCE VALUES(1,123);
INSERT INTO CONOCE VALUES(1,126);
INSERT INTO CONOCE VALUES(2,122); /* Ivysaur*/
INSERT INTO CONOCE VALUES(2,123);
INSERT INTO CONOCE VALUES(2,125);
INSERT INTO CONOCE VALUES(2,127);
INSERT INTO CONOCE VALUES(3,127); /* Venusaur*/
INSERT INTO CONOCE VALUES(3,125);
INSERT INTO CONOCE VALUES(3,120);
INSERT INTO CONOCE VALUES(3,121);
INSERT INTO CONOCE VALUES(4,23); /* Chamander*/
INSERT INTO CONOCE VALUES(4,24);
INSERT INTO CONOCE VALUES(4,25);
INSERT INTO CONOCE VALUES(4,26);
INSERT INTO CONOCE VALUES(5,28); /* Charmelon*/
INSERT INTO CONOCE VALUES(5,30);
INSERT INTO CONOCE VALUES(5,31);
INSERT INTO CONOCE VALUES(5,33);
INSERT INTO CONOCE VALUES(6,33); /* Charizard*/
INSERT INTO CONOCE VALUES(6,32);
INSERT INTO CONOCE VALUES(6,29);
INSERT INTO CONOCE VALUES(6,28);
INSERT INTO CONOCE VALUES(7,1); /* Squirtle*/
INSERT INTO CONOCE VALUES(7,2);
INSERT INTO CONOCE VALUES(7,8);
INSERT INTO CONOCE VALUES(7,5);
INSERT INTO CONOCE VALUES(8,5); /* Wartortle*/
INSERT INTO CONOCE VALUES(8,6);
INSERT INTO CONOCE VALUES(8,4);
INSERT INTO CONOCE VALUES(8,2);
INSERT INTO CONOCE VALUES(9,2); /* Blastoise*/
INSERT INTO CONOCE VALUES(9,3);
INSERT INTO CONOCE VALUES(9,4);
INSERT INTO CONOCE VALUES(9,5);
INSERT INTO CONOCE VALUES(10,119); /* Caterpie*/
INSERT INTO CONOCE VALUES(10,120);
INSERT INTO CONOCE VALUES(10,128);
INSERT INTO CONOCE VALUES(10,126);
INSERT INTO CONOCE VALUES(11,121); /* Metapod*/
INSERT INTO CONOCE VALUES(11,122);
INSERT INTO CONOCE VALUES(11,126);
INSERT INTO CONOCE VALUES(11,123);
INSERT INTO CONOCE VALUES(12,65); /* Butterfree*/
INSERT INTO CONOCE VALUES(12,64);
INSERT INTO CONOCE VALUES(12,77);
INSERT INTO CONOCE VALUES(12,100);
INSERT INTO CONOCE VALUES(13,119); /* Weedle*/
INSERT INTO CONOCE VALUES(13,125);
INSERT INTO CONOCE VALUES(13,126);
INSERT INTO CONOCE VALUES(13,122);
INSERT INTO CONOCE VALUES(14,122); /* Kakuna*/
INSERT INTO CONOCE VALUES(14,126);
INSERT INTO CONOCE VALUES(14,124);
INSERT INTO CONOCE VALUES(14,128);
INSERT INTO CONOCE VALUES(15,78); /* Beedrill*/
INSERT INTO CONOCE VALUES(15,95);
INSERT INTO CONOCE VALUES(15,65);
INSERT INTO CONOCE VALUES(15,63);
INSERT INTO CONOCE VALUES(16,159); /* Pidgey*/
INSERT INTO CONOCE VALUES(16,164);
INSERT INTO CONOCE VALUES(16,161);
INSERT INTO CONOCE VALUES(16,162);
INSERT INTO CONOCE VALUES(17,164); /* Pidgeotoo*/
INSERT INTO CONOCE VALUES(17,162);
INSERT INTO CONOCE VALUES(17,160);
INSERT INTO CONOCE VALUES(17,163);
INSERT INTO CONOCE VALUES(18,159); /* Pidgeot */
INSERT INTO CONOCE VALUES(18,160);
INSERT INTO CONOCE VALUES(18,164);
INSERT INTO CONOCE VALUES(18,163);
INSERT INTO CONOCE VALUES(19,80); /* Rattata */
INSERT INTO CONOCE VALUES(19,90);
INSERT INTO CONOCE VALUES(19,70);
INSERT INTO CONOCE VALUES(19,100);
INSERT INTO CONOCE VALUES(20,50); /* Raticate */
INSERT INTO CONOCE VALUES(20,51);
INSERT INTO CONOCE VALUES(20,52);
INSERT INTO CONOCE VALUES(20,56);
INSERT INTO CONOCE VALUES(21,164); /* Spearwow */
INSERT INTO CONOCE VALUES(21,163);
INSERT INTO CONOCE VALUES(21,162);
INSERT INTO CONOCE VALUES(21,161);
INSERT INTO CONOCE VALUES(22,160); /* Fearow */
INSERT INTO CONOCE VALUES(22,159);
INSERT INTO CONOCE VALUES(22,161);
INSERT INTO CONOCE VALUES(22,162);
INSERT INTO CONOCE VALUES(23,158); /* Ekans */
INSERT INTO CONOCE VALUES(23,151);
INSERT INTO CONOCE VALUES(23,155);
INSERT INTO CONOCE VALUES(23,153);
INSERT INTO CONOCE VALUES(24,153); /* Arbok */
INSERT INTO CONOCE VALUES(24,152);
INSERT INTO CONOCE VALUES(24,157);
INSERT INTO CONOCE VALUES(24,154);
INSERT INTO CONOCE VALUES(25,15); /* Pikachu */
INSERT INTO CONOCE VALUES(25,19);
INSERT INTO CONOCE VALUES(25,18);
INSERT INTO CONOCE VALUES(25,17);
INSERT INTO CONOCE VALUES(26,17); /* Raichu */
INSERT INTO CONOCE VALUES(26,18);
INSERT INTO CONOCE VALUES(26,15);
INSERT INTO CONOCE VALUES(26,16);
INSERT INTO CONOCE VALUES(27,149); /* Sandshrew */
INSERT INTO CONOCE VALUES(27,146);
INSERT INTO CONOCE VALUES(27,150);
INSERT INTO CONOCE VALUES(27,147);
INSERT INTO CONOCE VALUES(28,150); /* Sandslash */
INSERT INTO CONOCE VALUES(28,149);
INSERT INTO CONOCE VALUES(28,148);
INSERT INTO CONOCE VALUES(28,147);
INSERT INTO CONOCE VALUES(29,151); /* Nidoran */
INSERT INTO CONOCE VALUES(29,152);
INSERT INTO CONOCE VALUES(29,153);
INSERT INTO CONOCE VALUES(29,154);
INSERT INTO CONOCE VALUES(30,155); /* Nidorina */
INSERT INTO CONOCE VALUES(30,156);
INSERT INTO CONOCE VALUES(30,157);
INSERT INTO CONOCE VALUES(30,158);
INSERT INTO CONOCE VALUES(31,158); /* Nidoqueen */
INSERT INTO CONOCE VALUES(31,157);
INSERT INTO CONOCE VALUES(31,156);
INSERT INTO CONOCE VALUES(31,155);
INSERT INTO CONOCE VALUES(32,155); /* Nidoran */
INSERT INTO CONOCE VALUES(32,152);
INSERT INTO CONOCE VALUES(32,154);
INSERT INTO CONOCE VALUES(32,153);
INSERT INTO CONOCE VALUES(33,158); /* Nidorino */
INSERT INTO CONOCE VALUES(33,151);
INSERT INTO CONOCE VALUES(33,155);
INSERT INTO CONOCE VALUES(33,157);
INSERT INTO CONOCE VALUES(34,151); /* Nidoking */
INSERT INTO CONOCE VALUES(34,152);
INSERT INTO CONOCE VALUES(34,153);
INSERT INTO CONOCE VALUES(34,154);
INSERT INTO CONOCE VALUES(35,42); /* Cleafairy */
INSERT INTO CONOCE VALUES(35,43);
INSERT INTO CONOCE VALUES(35,44);
INSERT INTO CONOCE VALUES(35,45);
INSERT INTO CONOCE VALUES(36,46); /* Clefable */
INSERT INTO CONOCE VALUES(36,47);
INSERT INTO CONOCE VALUES(36,48);
INSERT INTO CONOCE VALUES(36,49);
INSERT INTO CONOCE VALUES(37,23); /* Vulpix */
INSERT INTO CONOCE VALUES(37,24);
INSERT INTO CONOCE VALUES(37,25);
INSERT INTO CONOCE VALUES(37,26);
INSERT INTO CONOCE VALUES(38,27); /* Ninetales */
INSERT INTO CONOCE VALUES(38,26);
INSERT INTO CONOCE VALUES(38,25);
INSERT INTO CONOCE VALUES(38,24);
INSERT INTO CONOCE VALUES(39,50); /* Jigglypuff */
INSERT INTO CONOCE VALUES(39,51);
INSERT INTO CONOCE VALUES(39,52);
INSERT INTO CONOCE VALUES(39,53);
INSERT INTO CONOCE VALUES(40,54); /* Wigglytuff */
INSERT INTO CONOCE VALUES(40,55);
INSERT INTO CONOCE VALUES(40,56);
INSERT INTO CONOCE VALUES(40,57);
INSERT INTO CONOCE VALUES(41,151); /* Zubat */
INSERT INTO CONOCE VALUES(41,152);
INSERT INTO CONOCE VALUES(41,153);
INSERT INTO CONOCE VALUES(41,154);
INSERT INTO CONOCE VALUES(42,155); /* Golbat */
INSERT INTO CONOCE VALUES(42,156);
INSERT INTO CONOCE VALUES(42,157);
INSERT INTO CONOCE VALUES(42,158);
INSERT INTO CONOCE VALUES(43,119); /* Oddish */
INSERT INTO CONOCE VALUES(43,120);
INSERT INTO CONOCE VALUES(43,121);
INSERT INTO CONOCE VALUES(43,122);
INSERT INTO CONOCE VALUES(44,123); /* Gloom */
INSERT INTO CONOCE VALUES(44,124);
INSERT INTO CONOCE VALUES(44,125);
INSERT INTO CONOCE VALUES(44,126);
INSERT INTO CONOCE VALUES(45,127); /* Vileplume */
INSERT INTO CONOCE VALUES(45,128);
INSERT INTO CONOCE VALUES(45,126);
INSERT INTO CONOCE VALUES(45,125);
INSERT INTO CONOCE VALUES(46,10); /* Paras */
INSERT INTO CONOCE VALUES(46,11);
INSERT INTO CONOCE VALUES(46,12);
INSERT INTO CONOCE VALUES(46,13);
INSERT INTO CONOCE VALUES(47,10); /* Parasect */
INSERT INTO CONOCE VALUES(47,11);
INSERT INTO CONOCE VALUES(47,12);
INSERT INTO CONOCE VALUES(47,13);
INSERT INTO CONOCE VALUES(48,13); /* Vemonat */
INSERT INTO CONOCE VALUES(48,12);
INSERT INTO CONOCE VALUES(48,11);
INSERT INTO CONOCE VALUES(48,10);
INSERT INTO CONOCE VALUES(49,13); /* Venomoth */
INSERT INTO CONOCE VALUES(49,12);
INSERT INTO CONOCE VALUES(49,120);
INSERT INTO CONOCE VALUES(49,121);
INSERT INTO CONOCE VALUES(50,146); /* Diglett */
INSERT INTO CONOCE VALUES(50,147);
INSERT INTO CONOCE VALUES(50,148);
INSERT INTO CONOCE VALUES(50,149);
INSERT INTO CONOCE VALUES(51,150); /* Dugtrio */
INSERT INTO CONOCE VALUES(51,149);
INSERT INTO CONOCE VALUES(51,148);
INSERT INTO CONOCE VALUES(51,147);
INSERT INTO CONOCE VALUES(52,60); /* Meowth*/
INSERT INTO CONOCE VALUES(52,61);
INSERT INTO CONOCE VALUES(52,62);
INSERT INTO CONOCE VALUES(52,63);
INSERT INTO CONOCE VALUES(53,64); /* Persian*/
INSERT INTO CONOCE VALUES(53,65);
INSERT INTO CONOCE VALUES(53,66);
INSERT INTO CONOCE VALUES(53,67);
INSERT INTO CONOCE VALUES(54,9); /* Psduck*/
INSERT INTO CONOCE VALUES(54,8);
INSERT INTO CONOCE VALUES(54,7);
INSERT INTO CONOCE VALUES(54,6);
INSERT INTO CONOCE VALUES(55,5); /* Golduck*/
INSERT INTO CONOCE VALUES(55,4);
INSERT INTO CONOCE VALUES(55,3);
INSERT INTO CONOCE VALUES(55,2);
INSERT INTO CONOCE VALUES(56,34); /* Mankey*/
INSERT INTO CONOCE VALUES(56,35);
INSERT INTO CONOCE VALUES(56,36);
INSERT INTO CONOCE VALUES(56,37);
INSERT INTO CONOCE VALUES(57,37); /* Primeape*/
INSERT INTO CONOCE VALUES(57,38);
INSERT INTO CONOCE VALUES(57,39);
INSERT INTO CONOCE VALUES(57,40);
INSERT INTO CONOCE VALUES(58,23); /* Growlithe*/
INSERT INTO CONOCE VALUES(58,24);
INSERT INTO CONOCE VALUES(58,25);
INSERT INTO CONOCE VALUES(58,26);
INSERT INTO CONOCE VALUES(59,27); /* Arcanine*/
INSERT INTO CONOCE VALUES(59,26);
INSERT INTO CONOCE VALUES(59,25);
INSERT INTO CONOCE VALUES(59,24);
INSERT INTO CONOCE VALUES(60,2); /* Poliwag*/
INSERT INTO CONOCE VALUES(60,1);
INSERT INTO CONOCE VALUES(60,3);
INSERT INTO CONOCE VALUES(60,4);
INSERT INTO CONOCE VALUES(61,5); /* Poliwhirl*/
INSERT INTO CONOCE VALUES(61,6);
INSERT INTO CONOCE VALUES(61,7);
INSERT INTO CONOCE VALUES(61,8);
INSERT INTO CONOCE VALUES(62,9); /* Poliwrath*/
INSERT INTO CONOCE VALUES(62,41);
INSERT INTO CONOCE VALUES(62,40);
INSERT INTO CONOCE VALUES(62,39);
INSERT INTO CONOCE VALUES(63,143); /* Abra*/
INSERT INTO CONOCE VALUES(63,142);
INSERT INTO CONOCE VALUES(63,141);
INSERT INTO CONOCE VALUES(63,140);
INSERT INTO CONOCE VALUES(64,139); /* Kadabra*/
INSERT INTO CONOCE VALUES(64,138);
INSERT INTO CONOCE VALUES(64,137);
INSERT INTO CONOCE VALUES(64,136);
INSERT INTO CONOCE VALUES(65,135); /* Alakazam*/
INSERT INTO CONOCE VALUES(65,134);
INSERT INTO CONOCE VALUES(65,133);
INSERT INTO CONOCE VALUES(65,132);
INSERT INTO CONOCE VALUES(66,34); /* Machop*/
INSERT INTO CONOCE VALUES(66,35);
INSERT INTO CONOCE VALUES(66,36);
INSERT INTO CONOCE VALUES(66,37);
INSERT INTO CONOCE VALUES(67,38); /* Machoke*/
INSERT INTO CONOCE VALUES(67,39);
INSERT INTO CONOCE VALUES(67,40);
INSERT INTO CONOCE VALUES(67,41);
INSERT INTO CONOCE VALUES(68,41); /* Machamp */
INSERT INTO CONOCE VALUES(68,40);
INSERT INTO CONOCE VALUES(68,39);
INSERT INTO CONOCE VALUES(68,38);
INSERT INTO CONOCE VALUES(69,119); /* Bellsprout */
INSERT INTO CONOCE VALUES(69,120);
INSERT INTO CONOCE VALUES(69,121);
INSERT INTO CONOCE VALUES(69,122);
INSERT INTO CONOCE VALUES(70,123); /* Weepinbell */
INSERT INTO CONOCE VALUES(70,124);
INSERT INTO CONOCE VALUES(70,125);
INSERT INTO CONOCE VALUES(70,126);
INSERT INTO CONOCE VALUES(71,127); /* Victreebel */
INSERT INTO CONOCE VALUES(71,128);
INSERT INTO CONOCE VALUES(71,151);
INSERT INTO CONOCE VALUES(71,152);
INSERT INTO CONOCE VALUES(72,1); /* Tentacool */
INSERT INTO CONOCE VALUES(72,2);
INSERT INTO CONOCE VALUES(72,3);
INSERT INTO CONOCE VALUES(72,151);
INSERT INTO CONOCE VALUES(73,151); /* Tentacruel */
INSERT INTO CONOCE VALUES(73,152);
INSERT INTO CONOCE VALUES(73,153);
INSERT INTO CONOCE VALUES(73,155);
INSERT INTO CONOCE VALUES(74,144); /* Geodude */
INSERT INTO CONOCE VALUES(74,145);
INSERT INTO CONOCE VALUES(74,146);
INSERT INTO CONOCE VALUES(74,147);
INSERT INTO CONOCE VALUES(75,148); /* Graveler */
INSERT INTO CONOCE VALUES(75,149);
INSERT INTO CONOCE VALUES(75,150);
INSERT INTO CONOCE VALUES(75,144);
INSERT INTO CONOCE VALUES(76,144); /* Golem */
INSERT INTO CONOCE VALUES(76,145);
INSERT INTO CONOCE VALUES(76,146);
INSERT INTO CONOCE VALUES(76,147);
INSERT INTO CONOCE VALUES(77,23); /* Ponyta */
INSERT INTO CONOCE VALUES(77,24);
INSERT INTO CONOCE VALUES(77,26);
INSERT INTO CONOCE VALUES(77,25);
INSERT INTO CONOCE VALUES(78,27); /* Rapidash */
INSERT INTO CONOCE VALUES(78,26);
INSERT INTO CONOCE VALUES(78,25);
INSERT INTO CONOCE VALUES(78,24);
INSERT INTO CONOCE VALUES(79,129); /* Slowpoke */
INSERT INTO CONOCE VALUES(79,130);
INSERT INTO CONOCE VALUES(79,131);
INSERT INTO CONOCE VALUES(79,132);
INSERT INTO CONOCE VALUES(80,133); /* Slowbro */
INSERT INTO CONOCE VALUES(80,134);
INSERT INTO CONOCE VALUES(80,135);
INSERT INTO CONOCE VALUES(80,136);
INSERT INTO CONOCE VALUES(81,15); /* Magnemite */
INSERT INTO CONOCE VALUES(81,16);
INSERT INTO CONOCE VALUES(81,17);
INSERT INTO CONOCE VALUES(81,18);
INSERT INTO CONOCE VALUES(82,19); /* Magneton */
INSERT INTO CONOCE VALUES(82,15);
INSERT INTO CONOCE VALUES(82,18);
INSERT INTO CONOCE VALUES(82,17);
INSERT INTO CONOCE VALUES(83,75); /* Farfetch d */
INSERT INTO CONOCE VALUES(83,76);
INSERT INTO CONOCE VALUES(83,77);
INSERT INTO CONOCE VALUES(83,78);
INSERT INTO CONOCE VALUES(84,79); /* Doduo */
INSERT INTO CONOCE VALUES(84,80);
INSERT INTO CONOCE VALUES(84,81);
INSERT INTO CONOCE VALUES(84,82);
INSERT INTO CONOCE VALUES(85,83); /* Dodrio */
INSERT INTO CONOCE VALUES(85,84);
INSERT INTO CONOCE VALUES(85,85);
INSERT INTO CONOCE VALUES(85,86);
INSERT INTO CONOCE VALUES(86,28); /* Seel */
INSERT INTO CONOCE VALUES(86,29);
INSERT INTO CONOCE VALUES(86,30);
INSERT INTO CONOCE VALUES(86,31);
INSERT INTO CONOCE VALUES(87,32); /* Dewgong */
INSERT INTO CONOCE VALUES(87,33);
INSERT INTO CONOCE VALUES(87,31);
INSERT INTO CONOCE VALUES(87,30);
INSERT INTO CONOCE VALUES(88,158); /* Grimer */
INSERT INTO CONOCE VALUES(88,157);
INSERT INTO CONOCE VALUES(88,156);
INSERT INTO CONOCE VALUES(88,155);
INSERT INTO CONOCE VALUES(89,154); /* Muk */
INSERT INTO CONOCE VALUES(89,153);
INSERT INTO CONOCE VALUES(89,152);
INSERT INTO CONOCE VALUES(89,151);
INSERT INTO CONOCE VALUES(90,1); /* Shellder */
INSERT INTO CONOCE VALUES(90,2);
INSERT INTO CONOCE VALUES(90,3);
INSERT INTO CONOCE VALUES(90,4);
INSERT INTO CONOCE VALUES(91,30); /* Cloyster */
INSERT INTO CONOCE VALUES(91,31);
INSERT INTO CONOCE VALUES(91,32);
INSERT INTO CONOCE VALUES(91,8);
INSERT INTO CONOCE VALUES(92,20); /* Gastly */
INSERT INTO CONOCE VALUES(92,21);
INSERT INTO CONOCE VALUES(92,22);
INSERT INTO CONOCE VALUES(92,155);
INSERT INTO CONOCE VALUES(93,156); /* Haunter */
INSERT INTO CONOCE VALUES(93,158);
INSERT INTO CONOCE VALUES(93,20);
INSERT INTO CONOCE VALUES(93,22);
INSERT INTO CONOCE VALUES(94,22); /* Gengar */
INSERT INTO CONOCE VALUES(94,21);
INSERT INTO CONOCE VALUES(94,20);
INSERT INTO CONOCE VALUES(94,151);
INSERT INTO CONOCE VALUES(95,144); /* Onix */
INSERT INTO CONOCE VALUES(95,145);
INSERT INTO CONOCE VALUES(95,146);
INSERT INTO CONOCE VALUES(95,145);
INSERT INTO CONOCE VALUES(96,129); /* Drowzee */
INSERT INTO CONOCE VALUES(96,130);
INSERT INTO CONOCE VALUES(96,131);
INSERT INTO CONOCE VALUES(96,132);
INSERT INTO CONOCE VALUES(97,133); /* Hypno */
INSERT INTO CONOCE VALUES(97,132);
INSERT INTO CONOCE VALUES(97,131);
INSERT INTO CONOCE VALUES(97,132);
INSERT INTO CONOCE VALUES(98,1); /* Krabby */
INSERT INTO CONOCE VALUES(98,2);
INSERT INTO CONOCE VALUES(98,3);
INSERT INTO CONOCE VALUES(98,4);
INSERT INTO CONOCE VALUES(99,5); /* Kingler */
INSERT INTO CONOCE VALUES(99,6);
INSERT INTO CONOCE VALUES(99,7);
INSERT INTO CONOCE VALUES(99,8);
INSERT INTO CONOCE VALUES(100,15); /* Voltorb */
INSERT INTO CONOCE VALUES(100,16);
INSERT INTO CONOCE VALUES(100,17);
INSERT INTO CONOCE VALUES(100,18);
INSERT INTO CONOCE VALUES(101,19); /* Electrode*/
INSERT INTO CONOCE VALUES(101,18);
INSERT INTO CONOCE VALUES(101,17);
INSERT INTO CONOCE VALUES(101,16);
INSERT INTO CONOCE VALUES(102,158); /* Exeggcute*/
INSERT INTO CONOCE VALUES(102,157);
INSERT INTO CONOCE VALUES(102,119);
INSERT INTO CONOCE VALUES(102,118);
INSERT INTO CONOCE VALUES(103,158); /* Exaggutor*/
INSERT INTO CONOCE VALUES(103,157);
INSERT INTO CONOCE VALUES(103,119);
INSERT INTO CONOCE VALUES(103,118);
INSERT INTO CONOCE VALUES(104,146); /* Cubone*/
INSERT INTO CONOCE VALUES(104,147);
INSERT INTO CONOCE VALUES(104,148);
INSERT INTO CONOCE VALUES(104,149);
INSERT INTO CONOCE VALUES(105,150); /* Marwak*/
INSERT INTO CONOCE VALUES(105,149);
INSERT INTO CONOCE VALUES(105,148);
INSERT INTO CONOCE VALUES(105,147);
INSERT INTO CONOCE VALUES(106,34); /* Hitmolle*/
INSERT INTO CONOCE VALUES(106,35);
INSERT INTO CONOCE VALUES(106,36);
INSERT INTO CONOCE VALUES(106,37);
INSERT INTO CONOCE VALUES(107,38); /* Hitmochan*/
INSERT INTO CONOCE VALUES(107,39);
INSERT INTO CONOCE VALUES(107,40);
INSERT INTO CONOCE VALUES(107,41);
INSERT INTO CONOCE VALUES(108,90); /* Lickitung*/
INSERT INTO CONOCE VALUES(108,91);
INSERT INTO CONOCE VALUES(108,92);
INSERT INTO CONOCE VALUES(108,93);
INSERT INTO CONOCE VALUES(109,151); /* Koffing*/
INSERT INTO CONOCE VALUES(109,158);
INSERT INTO CONOCE VALUES(109,155);
INSERT INTO CONOCE VALUES(109,153);
INSERT INTO CONOCE VALUES(110,153); /* Weezing*/
INSERT INTO CONOCE VALUES(110,152);
INSERT INTO CONOCE VALUES(110,151);
INSERT INTO CONOCE VALUES(110,155);
INSERT INTO CONOCE VALUES(111,146); /* Rhyhorn*/
INSERT INTO CONOCE VALUES(111,147);
INSERT INTO CONOCE VALUES(111,148);
INSERT INTO CONOCE VALUES(111,149);
INSERT INTO CONOCE VALUES(112,150); /* Rhydon*/
INSERT INTO CONOCE VALUES(112,149);
INSERT INTO CONOCE VALUES(112,148);
INSERT INTO CONOCE VALUES(112,147);
INSERT INTO CONOCE VALUES(113,100); /* Chansey*/
INSERT INTO CONOCE VALUES(113,101);
INSERT INTO CONOCE VALUES(113,102);
INSERT INTO CONOCE VALUES(113,103);
INSERT INTO CONOCE VALUES(114,128); /* Tangela*/
INSERT INTO CONOCE VALUES(114,127);
INSERT INTO CONOCE VALUES(114,126);
INSERT INTO CONOCE VALUES(114,125);
INSERT INTO CONOCE VALUES(115,124); /* Kangaskhan*/
INSERT INTO CONOCE VALUES(115,123);
INSERT INTO CONOCE VALUES(115,122);
INSERT INTO CONOCE VALUES(115,121);
INSERT INTO CONOCE VALUES(116,1); /* Horsea*/
INSERT INTO CONOCE VALUES(116,2);
INSERT INTO CONOCE VALUES(116,3);
INSERT INTO CONOCE VALUES(116,4);
INSERT INTO CONOCE VALUES(117,5); /* Seadra*/
INSERT INTO CONOCE VALUES(117,6);
INSERT INTO CONOCE VALUES(117,7);
INSERT INTO CONOCE VALUES(117,8);
INSERT INTO CONOCE VALUES(118,9); /* Goldeen */
INSERT INTO CONOCE VALUES(118,8);
INSERT INTO CONOCE VALUES(118,7);
INSERT INTO CONOCE VALUES(118,6);
INSERT INTO CONOCE VALUES(119,5); /* Seaking */
INSERT INTO CONOCE VALUES(119,4);
INSERT INTO CONOCE VALUES(119,3);
INSERT INTO CONOCE VALUES(119,2);
INSERT INTO CONOCE VALUES(120,1); /* Staryu */
INSERT INTO CONOCE VALUES(120,2);
INSERT INTO CONOCE VALUES(120,3);
INSERT INTO CONOCE VALUES(120,4);
INSERT INTO CONOCE VALUES(121,143); /* Starmie */
INSERT INTO CONOCE VALUES(121,142);
INSERT INTO CONOCE VALUES(121,141);
INSERT INTO CONOCE VALUES(121,140);
INSERT INTO CONOCE VALUES(122,139); /* Mr.Mime */
INSERT INTO CONOCE VALUES(122,138);
INSERT INTO CONOCE VALUES(122,137);
INSERT INTO CONOCE VALUES(122,136);
INSERT INTO CONOCE VALUES(123,10); /* Scyther */
INSERT INTO CONOCE VALUES(123,11);
INSERT INTO CONOCE VALUES(123,12);
INSERT INTO CONOCE VALUES(123,13);
INSERT INTO CONOCE VALUES(124,33); /* Jynx */
INSERT INTO CONOCE VALUES(124,28);
INSERT INTO CONOCE VALUES(124,29);
INSERT INTO CONOCE VALUES(124,32);
INSERT INTO CONOCE VALUES(125,19); /* Electabuzz */
INSERT INTO CONOCE VALUES(125,18);
INSERT INTO CONOCE VALUES(125,17);
INSERT INTO CONOCE VALUES(125,16);
INSERT INTO CONOCE VALUES(126,27); /* Magmar */
INSERT INTO CONOCE VALUES(126,26);
INSERT INTO CONOCE VALUES(126,25);
INSERT INTO CONOCE VALUES(126,24);
INSERT INTO CONOCE VALUES(127,10); /* Pinsir */
INSERT INTO CONOCE VALUES(127,11);
INSERT INTO CONOCE VALUES(127,12);
INSERT INTO CONOCE VALUES(127,13);
INSERT INTO CONOCE VALUES(128,110); /* Tauros */
INSERT INTO CONOCE VALUES(128,111);
INSERT INTO CONOCE VALUES(128,112);
INSERT INTO CONOCE VALUES(128,113);
INSERT INTO CONOCE VALUES(129,110); /* Magikarp */
INSERT INTO CONOCE VALUES(130,159); /* Gyarados */
INSERT INTO CONOCE VALUES(130,160);
INSERT INTO CONOCE VALUES(130,161);
INSERT INTO CONOCE VALUES(130,5);
INSERT INTO CONOCE VALUES(131,5); /* Lapras */
INSERT INTO CONOCE VALUES(131,9);
INSERT INTO CONOCE VALUES(131,28);
INSERT INTO CONOCE VALUES(131,33);
INSERT INTO CONOCE VALUES(132,115); /* Ditto */
INSERT INTO CONOCE VALUES(133,118); /* Eevee */
INSERT INTO CONOCE VALUES(133,116);
INSERT INTO CONOCE VALUES(133,114);
INSERT INTO CONOCE VALUES(133,113);
INSERT INTO CONOCE VALUES(134,1); /* Vaporeon */
INSERT INTO CONOCE VALUES(134,2);
INSERT INTO CONOCE VALUES(134,3);
INSERT INTO CONOCE VALUES(134,4);
INSERT INTO CONOCE VALUES(135,15); /* Jolteon */
INSERT INTO CONOCE VALUES(135,16);
INSERT INTO CONOCE VALUES(135,17);
INSERT INTO CONOCE VALUES(135,19);
INSERT INTO CONOCE VALUES(136,27); /* Flareon */
INSERT INTO CONOCE VALUES(136,25);
INSERT INTO CONOCE VALUES(136,24);
INSERT INTO CONOCE VALUES(136,23);
INSERT INTO CONOCE VALUES(137,99); /* Porygon */
INSERT INTO CONOCE VALUES(137,98);
INSERT INTO CONOCE VALUES(137,97);
INSERT INTO CONOCE VALUES(137,96);
INSERT INTO CONOCE VALUES(138,9); /* Omanyte */
INSERT INTO CONOCE VALUES(138,144);
INSERT INTO CONOCE VALUES(138,145);
INSERT INTO CONOCE VALUES(138,7);
INSERT INTO CONOCE VALUES(139,144); /* Omastar */
INSERT INTO CONOCE VALUES(139,145);
INSERT INTO CONOCE VALUES(139,7);
INSERT INTO CONOCE VALUES(139,1);
INSERT INTO CONOCE VALUES(140,7); /* Kabuto */
INSERT INTO CONOCE VALUES(140,8);
INSERT INTO CONOCE VALUES(140,9);
INSERT INTO CONOCE VALUES(140,144);
INSERT INTO CONOCE VALUES(141,144); /* Kabutops */
INSERT INTO CONOCE VALUES(141,145);
INSERT INTO CONOCE VALUES(141,5);
INSERT INTO CONOCE VALUES(141,6);
INSERT INTO CONOCE VALUES(142,164); /* Aerodactyl */
INSERT INTO CONOCE VALUES(142,161);
INSERT INTO CONOCE VALUES(142,159);
INSERT INTO CONOCE VALUES(142,163);
INSERT INTO CONOCE VALUES(143,89); /* Snorlax */
INSERT INTO CONOCE VALUES(143,88);
INSERT INTO CONOCE VALUES(143,87);
INSERT INTO CONOCE VALUES(143,86);
INSERT INTO CONOCE VALUES(144,164); /* Articuno */
INSERT INTO CONOCE VALUES(144,33);
INSERT INTO CONOCE VALUES(144,31);
INSERT INTO CONOCE VALUES(144,29);
INSERT INTO CONOCE VALUES(145,19); /* Zapdos */
INSERT INTO CONOCE VALUES(145,18);
INSERT INTO CONOCE VALUES(145,17);
INSERT INTO CONOCE VALUES(145,16);
INSERT INTO CONOCE VALUES(146,23); /* Moltres */
INSERT INTO CONOCE VALUES(146,24);
INSERT INTO CONOCE VALUES(146,25);
INSERT INTO CONOCE VALUES(146,26);
INSERT INTO CONOCE VALUES(147,14); /* Dratini */
INSERT INTO CONOCE VALUES(147,26);
INSERT INTO CONOCE VALUES(147,71);
INSERT INTO CONOCE VALUES(147,25);
INSERT INTO CONOCE VALUES(148,14); /* Dragonair */
INSERT INTO CONOCE VALUES(148,26);
INSERT INTO CONOCE VALUES(148,25);
INSERT INTO CONOCE VALUES(148,71);
INSERT INTO CONOCE VALUES(149,14); /* Dragonite */
INSERT INTO CONOCE VALUES(149,26);
INSERT INTO CONOCE VALUES(149,25);
INSERT INTO CONOCE VALUES(149,164);
INSERT INTO CONOCE VALUES(150,133); /* Mewtwo */
INSERT INTO CONOCE VALUES(150,139);
INSERT INTO CONOCE VALUES(150,140);
INSERT INTO CONOCE VALUES(150,141);
INSERT INTO CONOCE VALUES(151,138); /* Mew */
INSERT INTO CONOCE VALUES(151,139);
INSERT INTO CONOCE VALUES(151,140);
INSERT INTO CONOCE VALUES(151,141);


/**
 * ESTADOS
*/

INSERT INTO ESTADO VALUES (1,"Paralizado",1,"Puede evitar que el pokemon ataque");
INSERT INTO ESTADO VALUES (2,"Quemado",1,"Dania al pokemon cada ronda");
INSERT INTO ESTADO VALUES (3,"Envenenado",1,"Dania al pokemon cada ronda exponencialmente");
INSERT INTO ESTADO VALUES (4,"Dormido",1,"Duerme al pokemon");
INSERT INTO ESTADO VALUES (5,"Congelado",1,"Puede evitar que el pokemon ataque");
INSERT INTO ESTADO VALUES (6,"Confuso",2,"Puede evitar que el pokemon ataque y que se haga danio");
INSERT INTO ESTADO VALUES (7,"Enamorado",2,"Puede evitar que el pokemon ataque");
INSERT INTO ESTADO VALUES (8,"Drenado",2,"Roba vida del pokemon y se la da al atacante");
INSERT INTO ESTADO VALUES (9,"Maldito",2,"Dania al pokemon");
INSERT INTO ESTADO VALUES (10,"Atrapado",2,"Evita que el pokemon huya");

/**
 * ENTRENADORES
*/

INSERT INTO ENTRENADOR VALUES (1,"Azul");
INSERT INTO ENTRENADOR VALUES (2,"Lorelei");
INSERT INTO ENTRENADOR VALUES (3,"Bruno");
INSERT INTO ENTRENADOR VALUES (4,"Agatha");
INSERT INTO ENTRENADOR VALUES (5,"Lance");
INSERT INTO ENTRENADOR VALUES (6,"Brock");
INSERT INTO ENTRENADOR VALUES (7,"Mysty");
INSERT INTO ENTRENADOR VALUES (8,"Lt. Surge");
INSERT INTO ENTRENADOR VALUES (9,"Erika");
INSERT INTO ENTRENADOR VALUES (10,"Koga");
INSERT INTO ENTRENADOR VALUES (11,"Sabrina");
INSERT INTO ENTRENADOR VALUES (12,"Blaine");
INSERT INTO ENTRENADOR VALUES (13,"Giovanni");
INSERT INTO ENTRENADOR VALUES (14,"Jessie");
INSERT INTO ENTRENADOR VALUES (15,"James");
INSERT INTO ENTRENADOR VALUES (16,"Admin Ruben");
INSERT INTO ENTRENADOR VALUES (17,"Admin Jose Manuel");
INSERT INTO ENTRENADOR VALUES (18,"Andres");
INSERT INTO ENTRENADOR VALUES (19,"Yessica");
INSERT INTO ENTRENADOR VALUES (20,"Danielle");
INSERT INTO ENTRENADOR VALUES (21,"Ruben");
INSERT INTO ENTRENADOR VALUES (22,"Ridel");
INSERT INTO ENTRENADOR VALUES (23,"Cristian");
INSERT INTO ENTRENADOR VALUES (24,"Alejandro");
INSERT INTO ENTRENADOR VALUES (25,"Gersan");
INSERT INTO ENTRENADOR VALUES (26,"Profesor Alejandro");
INSERT INTO ENTRENADOR VALUES (27,"Profesor Johatham");
INSERT INTO ENTRENADOR VALUES (28,"Profesor Oak");

/**
 * CAMPEON DE LA LIGA
*/

INSERT INTO CAMPEON_LIGA VALUES (1,"Johto");

/**
 * ALTO MANDO
*/

INSERT INTO ALTO_MANDO VALUES (2,"Hielo");
INSERT INTO ALTO_MANDO VALUES (3,"Lucha");
INSERT INTO ALTO_MANDO VALUES (4,"Veneno");
INSERT INTO ALTO_MANDO VALUES (5,"Dragon");

/**
 * LIDERES DE GIMNASIO
*/

INSERT INTO LIDER_GIMNASIO VALUES (6,1);
INSERT INTO LIDER_GIMNASIO VALUES (7,2);
INSERT INTO LIDER_GIMNASIO VALUES (8,3);
INSERT INTO LIDER_GIMNASIO VALUES (9,4);
INSERT INTO LIDER_GIMNASIO VALUES (10,5);
INSERT INTO LIDER_GIMNASIO VALUES (11,6);
INSERT INTO LIDER_GIMNASIO VALUES (12,7);
INSERT INTO LIDER_GIMNASIO VALUES (13,8);

/**
 * VILLANOS
*/

INSERT INTO VILLANO VALUES (13,"Dominar el universo usando a todos los Pokemon");
INSERT INTO VILLANO VALUES (14,"Conseguir pokemons para el Team Rocket");
INSERT INTO VILLANO VALUES (15,"Conseguir pokemons para el Team Rocket");

/**
 * ENTRENADORES CASUALES
*/

INSERT INTO ENTRENADOR_CASUAL VALUES (16,8);
INSERT INTO ENTRENADOR_CASUAL VALUES (17,8);
INSERT INTO ENTRENADOR_CASUAL VALUES (18,7);
INSERT INTO ENTRENADOR_CASUAL VALUES (19,5);
INSERT INTO ENTRENADOR_CASUAL VALUES (20,3);
INSERT INTO ENTRENADOR_CASUAL VALUES (21,7);
INSERT INTO ENTRENADOR_CASUAL VALUES (22,6);
INSERT INTO ENTRENADOR_CASUAL VALUES (23,6);
INSERT INTO ENTRENADOR_CASUAL VALUES (24,5);
INSERT INTO ENTRENADOR_CASUAL VALUES (25,5);
INSERT INTO ENTRENADOR_CASUAL VALUES (26,1);
INSERT INTO ENTRENADOR_CASUAL VALUES (27,1);
INSERT INTO ENTRENADOR_CASUAL VALUES (28,8);

/**
 * TIENE
*/

INSERT INTO TIENE VALUES (1,18,1); /* Azul */
INSERT INTO TIENE VALUES (1,65,1); 
INSERT INTO TIENE VALUES (1,112,1);
INSERT INTO TIENE VALUES (1,103,1);
INSERT INTO TIENE VALUES (1,130,1);
INSERT INTO TIENE VALUES (1,6,1);
INSERT INTO TIENE VALUES (2,87,1); /* Lorelei */
INSERT INTO TIENE VALUES (2,91,1);
INSERT INTO TIENE VALUES (2,80,1);
INSERT INTO TIENE VALUES (2,124,1);
INSERT INTO TIENE VALUES (2,131,1);
INSERT INTO TIENE VALUES (3,95,2); /* Bruno */
INSERT INTO TIENE VALUES (3,107,1);
INSERT INTO TIENE VALUES (3,106,1);
INSERT INTO TIENE VALUES (3,68,1);
INSERT INTO TIENE VALUES (4,94,2); /* Agatha */
INSERT INTO TIENE VALUES (4,42,1);
INSERT INTO TIENE VALUES (4,93,1);
INSERT INTO TIENE VALUES (4,24,1);
INSERT INTO TIENE VALUES (5,149,1); /* Lance */
INSERT INTO TIENE VALUES (5,148,2);
INSERT INTO TIENE VALUES (5,130,1);
INSERT INTO TIENE VALUES (5,142,1);
INSERT INTO TIENE VALUES (6,74,1); /* Brock */
INSERT INTO TIENE VALUES (6,95,1);
INSERT INTO TIENE VALUES (7,120,1); /* Mysty */
INSERT INTO TIENE VALUES (7,121,1);
INSERT INTO TIENE VALUES (8,100,1); /* Lt. Surge */
INSERT INTO TIENE VALUES (8,25,1);
INSERT INTO TIENE VALUES (8,26,1);
INSERT INTO TIENE VALUES (9,71,1); /* Erika */
INSERT INTO TIENE VALUES (9,114,1);
INSERT INTO TIENE VALUES (9,45,1);
INSERT INTO TIENE VALUES (10,109,2); /* Koga */
INSERT INTO TIENE VALUES (10,89,1);
INSERT INTO TIENE VALUES (10,110,1);
INSERT INTO TIENE VALUES (11,64,1); /* Sabrina */
INSERT INTO TIENE VALUES (11,49,1);
INSERT INTO TIENE VALUES (11,122,1);
INSERT INTO TIENE VALUES (11,65,1);
INSERT INTO TIENE VALUES (12,58,1); /* Blaine */
INSERT INTO TIENE VALUES (12,77,1);
INSERT INTO TIENE VALUES (12,78,1);
INSERT INTO TIENE VALUES (12,59,1);
INSERT INTO TIENE VALUES (13,111,2); /* Giovanni */
INSERT INTO TIENE VALUES (13,51,1);
INSERT INTO TIENE VALUES (13,34,1);
INSERT INTO TIENE VALUES (13,31,1);
INSERT INTO TIENE VALUES (14,24,2); /* Jessie */
INSERT INTO TIENE VALUES (14,110,1);
INSERT INTO TIENE VALUES (14,52,1);
INSERT INTO TIENE VALUES (15,24,2); /* James */
INSERT INTO TIENE VALUES (15,110,1);
INSERT INTO TIENE VALUES (15,52,1);
INSERT INTO TIENE VALUES (16,65,1); /* Admin Ruben */
INSERT INTO TIENE VALUES (17,68,1); /* Admin Jose Manuel */
INSERT INTO TIENE VALUES (18,151,1); /* Andres */
INSERT INTO TIENE VALUES (19,133,1); /* Yessica */
INSERT INTO TIENE VALUES (20,149,1); /* Danielle */
INSERT INTO TIENE VALUES (21,65,1); /* Ruben */
INSERT INTO TIENE VALUES (22,94,1); /* Ridel */
INSERT INTO TIENE VALUES (23,9,1); /* Cristian */
INSERT INTO TIENE VALUES (24,144,1); /* Alejandro */
INSERT INTO TIENE VALUES (25,39,1); /* Gersan */
INSERT INTO TIENE VALUES (26,6,1); /* Profesor Alejandro */
INSERT INTO TIENE VALUES (27,151,1); /* Profesor Johatham */
INSERT INTO TIENE VALUES (28,133,1); /* Profesor Oak */

/**
 * Objetos
*/

INSERT INTO OBJETO VALUES (1,"Pokedex","Entregado",NULL);
INSERT INTO OBJETO VALUES (2,"Mapa","Entregado",NULL);
INSERT INTO OBJETO VALUES (3,"Bicicleta","Entregado",NULL);
INSERT INTO OBJETO VALUES (4,"Bono bici","Entregado",NULL);
INSERT INTO OBJETO VALUES (5,"Cania vieja","Entregado",NULL);
INSERT INTO OBJETO VALUES (6,"Cania buena","Entregado",NULL);
INSERT INTO OBJETO VALUES (7,"Supercania","Entregado",NULL);
INSERT INTO OBJETO VALUES (8,"Fosil domo","Entregado",500);
INSERT INTO OBJETO VALUES (9,"Fosil helix","Entregado",500);
INSERT INTO OBJETO VALUES (10,"Monedero","Entregado",NULL);
INSERT INTO OBJETO VALUES (11,"Pokeflauta","Entregado",NULL);
INSERT INTO OBJETO VALUES (12,"Poke Ball","Comprado",100);
INSERT INTO OBJETO VALUES (13,"Super Ball","Comprado",300);
INSERT INTO OBJETO VALUES (14,"Ultra Ball","Comprado",600);
INSERT INTO OBJETO VALUES (15,"Master Ball","Entregado",NULL);
INSERT INTO OBJETO VALUES (16,"Safari Ball","Comprado",NULL);
INSERT INTO OBJETO VALUES (17,"MO01 Corte","Entregado",NULL);
INSERT INTO OBJETO VALUES (18,"MO02 Vuelo","Recogido",NULL);
INSERT INTO OBJETO VALUES (19,"MO03 Surf","Recogido",NULL);
INSERT INTO OBJETO VALUES (20,"MO04 Fuerza","Entregado",NULL);
INSERT INTO OBJETO VALUES (21,"MO05 Destello","Entregado",NULL);
INSERT INTO OBJETO VALUES (22,"MT01 Megapunio","Comprado",NULL);
INSERT INTO OBJETO VALUES (23,"MT02 Viento Cortante","Comprado",NULL);
INSERT INTO OBJETO VALUES (24,"MT03 Danza Espada","Recogido",NULL);
INSERT INTO OBJETO VALUES (25,"MT04 Remolino","Recogido",NULL);
INSERT INTO OBJETO VALUES (26,"MT05 Megapatada","Comprado",NULL);
INSERT INTO OBJETO VALUES (27,"MT06 Toxico","Entregado",NULL);
INSERT INTO OBJETO VALUES (28,"MT07 Perforador","Comprado",NULL);
INSERT INTO OBJETO VALUES (29,"MT08 Golpe Cuerpo","Recodigo",NULL);
INSERT INTO OBJETO VALUES (30,"MT09 Derribo","Comprado",NULL);
INSERT INTO OBJETO VALUES (31,"MT10 Doble Filo","Recogido",NULL);
INSERT INTO OBJETO VALUES (32,"MT11 Rayo Burbuja","Entregado",NULL);
INSERT INTO OBJETO VALUES (33,"MT12 Pistola Agua","Recogido",NULL);
INSERT INTO OBJETO VALUES (34,"MT13 Rayo Hielo","Recogido",NULL);
INSERT INTO OBJETO VALUES (35,"MT14 Ventisca","Recogido",NULL);
INSERT INTO OBJETO VALUES (36,"MT15 Hiperrayo","Comprado",NULL);
INSERT INTO OBJETO VALUES (37,"MT16 Dia de pago","Recogido",NULL);
INSERT INTO OBJETO VALUES (38,"MT17 Sumision","Comprado",NULL);
INSERT INTO OBJETO VALUES (39,"MT18 Contraataque","Recogido",NULL);
INSERT INTO OBJETO VALUES (40,"MT19 Movimineto Sismico","Recogido",NULL);
INSERT INTO OBJETO VALUES (41,"MT20 Furia","Recogido",NULL);
INSERT INTO OBJETO VALUES (42,"MT21 Megaagotar","Entregado",NULL);
INSERT INTO OBJETO VALUES (43,"MT22 Rayo solar","Recogido",NULL);
INSERT INTO OBJETO VALUES (44,"MT23 Furia dragon","Comprado",NULL);
INSERT INTO OBJETO VALUES (45,"MT24 Rayo","Entregado",NULL);
INSERT INTO OBJETO VALUES (46,"MT25 Trueno","Recogido",NULL);
INSERT INTO OBJETO VALUES (47,"MT26 Terremoto","Recogido",NULL);
INSERT INTO OBJETO VALUES (48,"MT27 Fisura","Entregado",NULL);
INSERT INTO OBJETO VALUES (49,"MT28 Excavar","Recogido",NULL);
INSERT INTO OBJETO VALUES (50,"MT29 Psiquico","Recogido",NULL);
INSERT INTO OBJETO VALUES (51,"MT30 Teletransporte","Recogido",NULL);
INSERT INTO OBJETO VALUES (52,"MT31 Mimetico","Recogido",NULL);
INSERT INTO OBJETO VALUES (53,"MT32 Doble Equipo","Comprado",NULL);
INSERT INTO OBJETO VALUES (54,"MT33 Reflejo","Comprado",NULL);
INSERT INTO OBJETO VALUES (55,"MT34 Venganza","Entregado",NULL);
INSERT INTO OBJETO VALUES (56,"MT35 Metronomo","Recogido",NULL);
INSERT INTO OBJETO VALUES (57,"MT36 Autodestruccion","Recogido",NULL);
INSERT INTO OBJETO VALUES (58,"MT37 Bomba huevo","Comprado",NULL);
INSERT INTO OBJETO VALUES (59,"MT38 LLamarada","Entregado",NULL);
INSERT INTO OBJETO VALUES (60,"MT39 Rapidez","Recogido",NULL);
INSERT INTO OBJETO VALUES (61,"MT40 Cabezazo","Recogido",NULL);
INSERT INTO OBJETO VALUES (62,"MT41 Amortiguador","Recogido",NULL);
INSERT INTO OBJETO VALUES (63,"MT42 Come suenios","Recogido",NULL);
INSERT INTO OBJETO VALUES (64,"MT43 Ataque aereo","Recogido",NULL);
INSERT INTO OBJETO VALUES (65,"MT44 Descanso","Recogido",NULL);
INSERT INTO OBJETO VALUES (66,"MT45 Onda trueno","Recogido",NULL);
INSERT INTO OBJETO VALUES (67,"MT46 Psicoonda","Entregado",NULL);
INSERT INTO OBJETO VALUES (68,"MT47 Explosion","Recogido",NULL);
INSERT INTO OBJETO VALUES (69,"MT48 Avalancha","Recogido",NULL);
INSERT INTO OBJETO VALUES (70,"MT49 Triataque","Recogido",NULL);
INSERT INTO OBJETO VALUES (71,"MT50 Sustituto","Comprado",NULL);

/**
 * OBJETOS COMUNES
*/

INSERT INTO OBJETO_COMUN VALUES (1,"Muestra informacion sobre los pokemon");
INSERT INTO OBJETO_COMUN VALUES (2,"Muestra una imagen de la región en la que estas");
INSERT INTO OBJETO_COMUN VALUES (3,"Te permite desplazarte mas rapido");
INSERT INTO OBJETO_COMUN VALUES (4,"Te permite conseguir una bicicleta");
INSERT INTO OBJETO_COMUN VALUES (5,"Te permite pescar con dificultad");
INSERT INTO OBJETO_COMUN VALUES (6,"Te permite pescar con mas facilidad");
INSERT INTO OBJETO_COMUN VALUES (7,"Te permite pescar facilmente");
INSERT INTO OBJETO_COMUN VALUES (8,"Te permite conseguir a Kabuto");
INSERT INTO OBJETO_COMUN VALUES (9,"Te permite conseguir a Omanyte");
INSERT INTO OBJETO_COMUN VALUES (10,"Te permite guardar el dinero");
INSERT INTO OBJETO_COMUN VALUES (11,"Te permite despertar a Snorlax");

/**
 * POKE BALLS
*/

INSERT INTO POKEBALL VALUES (12,1);
INSERT INTO POKEBALL VALUES (13,1.5);
INSERT INTO POKEBALL VALUES (14,2);
INSERT INTO POKEBALL VALUES (15,255);
INSERT INTO POKEBALL VALUES (16,1.5);

/**
 * MAQUINAS
*/

INSERT INTO MAQUINA VALUES (17,61);
INSERT INTO MAQUINA VALUES (18,164);
INSERT INTO MAQUINA VALUES (19,8);
INSERT INTO MAQUINA VALUES (20,76);
INSERT INTO MAQUINA VALUES (21,67);
INSERT INTO MAQUINA VALUES (22,90);
INSERT INTO MAQUINA VALUES (23,118);
INSERT INTO MAQUINA VALUES (24,120);
INSERT INTO MAQUINA VALUES (25,105);
INSERT INTO MAQUINA VALUES (26,89);
INSERT INTO MAQUINA VALUES (27,157);
INSERT INTO MAQUINA VALUES (28,95);
INSERT INTO MAQUINA VALUES (29,80);
INSERT INTO MAQUINA VALUES (30,64);
INSERT INTO MAQUINA VALUES (31,71);
INSERT INTO MAQUINA VALUES (32,1);
INSERT INTO MAQUINA VALUES (33,5);
INSERT INTO MAQUINA VALUES (34,32);
INSERT INTO MAQUINA VALUES (35,33);
INSERT INTO MAQUINA VALUES (36,86);
INSERT INTO MAQUINA VALUES (37,69);
INSERT INTO MAQUINA VALUES (38,41);
INSERT INTO MAQUINA VALUES (39,34);
INSERT INTO MAQUINA VALUES (40,36);
INSERT INTO MAQUINA VALUES (41,49);
INSERT INTO MAQUINA VALUES (42,125);
INSERT INTO MAQUINA VALUES (43,127);
INSERT INTO MAQUINA VALUES (44,14);
INSERT INTO MAQUINA VALUES (45,18);
INSERT INTO MAQUINA VALUES (46,19);
INSERT INTO MAQUINA VALUES (47,150);
INSERT INTO MAQUINA VALUES (48,147);
INSERT INTO MAQUINA VALUES (49,146);
INSERT INTO MAQUINA VALUES (50,141);
INSERT INTO MAQUINA VALUES (51,143);
INSERT INTO MAQUINA VALUES (52,92);
INSERT INTO MAQUINA VALUES (53,70);
INSERT INTO MAQUINA VALUES (54,142);
INSERT INTO MAQUINA VALUES (55,117);
INSERT INTO MAQUINA VALUES (56,91);
INSERT INTO MAQUINA VALUES (57,51);
INSERT INTO MAQUINA VALUES (58,53);
INSERT INTO MAQUINA VALUES (59,26);
INSERT INTO MAQUINA VALUES (60,102);
INSERT INTO MAQUINA VALUES (61,55);
INSERT INTO MAQUINA VALUES (62,44);
INSERT INTO MAQUINA VALUES (63,132);
INSERT INTO MAQUINA VALUES (64,160);
INSERT INTO MAQUINA VALUES (65,134);
INSERT INTO MAQUINA VALUES (66,16);
INSERT INTO MAQUINA VALUES (67,139);
INSERT INTO MAQUINA VALUES (68,73);
INSERT INTO MAQUINA VALUES (69,144);
INSERT INTO MAQUINA VALUES (70,116);
INSERT INTO MAQUINA VALUES (71,113);

/**
 * ENTRENADOR EQUIPA
*/

INSERT INTO ENTRENADOR_EQUIPA VALUES (1,1,1);
INSERT INTO ENTRENADOR_EQUIPA VALUES (2,10,1);
INSERT INTO ENTRENADOR_EQUIPA VALUES (3,10,1);
INSERT INTO ENTRENADOR_EQUIPA VALUES (4,10,1);
INSERT INTO ENTRENADOR_EQUIPA VALUES (5,10,1);
INSERT INTO ENTRENADOR_EQUIPA VALUES (6,10,1);
INSERT INTO ENTRENADOR_EQUIPA VALUES (7,10,1);
INSERT INTO ENTRENADOR_EQUIPA VALUES (8,10,1);
INSERT INTO ENTRENADOR_EQUIPA VALUES (9,4,1);
INSERT INTO ENTRENADOR_EQUIPA VALUES (10,4,1);
INSERT INTO ENTRENADOR_EQUIPA VALUES (11,5,1);
INSERT INTO ENTRENADOR_EQUIPA VALUES (12,4,1);
INSERT INTO ENTRENADOR_EQUIPA VALUES (13,6,1);
INSERT INTO ENTRENADOR_EQUIPA VALUES (14,5,1);
INSERT INTO ENTRENADOR_EQUIPA VALUES (15,2,1);
INSERT INTO ENTRENADOR_EQUIPA VALUES (16,2,1);
INSERT INTO ENTRENADOR_EQUIPA VALUES (17,2,1);
INSERT INTO ENTRENADOR_EQUIPA VALUES (18,2,1);
INSERT INTO ENTRENADOR_EQUIPA VALUES (19,2,1);
INSERT INTO ENTRENADOR_EQUIPA VALUES (20,2,1);
INSERT INTO ENTRENADOR_EQUIPA VALUES (21,2,1);
INSERT INTO ENTRENADOR_EQUIPA VALUES (22,2,1);
INSERT INTO ENTRENADOR_EQUIPA VALUES (23,2,1);
INSERT INTO ENTRENADOR_EQUIPA VALUES (24,2,1);
INSERT INTO ENTRENADOR_EQUIPA VALUES (25,2,1);
INSERT INTO ENTRENADOR_EQUIPA VALUES (26,10,1);
INSERT INTO ENTRENADOR_EQUIPA VALUES (27,1,1);
INSERT INTO ENTRENADOR_EQUIPA VALUES (28,1,1);

/**
 * POKEMON EQUIPA
*/

INSERT INTO POKEMON_EQUIPA VALUES (143,11);
INSERT INTO POKEMON_EQUIPA VALUES (138,8);
INSERT INTO POKEMON_EQUIPA VALUES (140,9);
INSERT INTO POKEMON_EQUIPA VALUES (52,10);
INSERT INTO POKEMON_EQUIPA VALUES (130,6);
