/**
 * Script de insercion de datos
*/

/**
 * ESTADISTICAS BASE
*/

/**
 * CARACTERISTICAS
*/

/**
 * POKEMONS
*/

/**
 * EVOLUCIONES
*/

/**
 * MOVIMIENTOS
*/

/**
 * CONOCE
*/

/**
 * ESTADOS
*/

/**
 * ENTRENADORES
*/

INSERT INTO ENTRENADOR VALUES (1,"Azul");
INSERT INTO ENTRENADOR VALUES (2,"Lorelei");
INSERT INTO ENTRENADOR VALUES (3,"Bruno");
INSERT INTO ENTRENADOR VALUES (4,"Agatha");
INSERT INTO ENTRENADOR VALUES (5,"Lance");
INSERT INTO ENTRENADOR VALUES (6,"Brock");
INSERT INTO ENTRENADOR VALUES (7,"Mysty");
INSERT INTO ENTRENADOR VALUES (8,"Lt. Surge");
INSERT INTO ENTRENADOR VALUES (9,"Erika");
INSERT INTO ENTRENADOR VALUES (10,"Koga");
INSERT INTO ENTRENADOR VALUES (11,"Sabrina");
INSERT INTO ENTRENADOR VALUES (12,"Blaine");
INSERT INTO ENTRENADOR VALUES (13,"Giovanni");
INSERT INTO ENTRENADOR VALUES (14,"Jessie");
INSERT INTO ENTRENADOR VALUES (15,"James");
INSERT INTO ENTRENADOR VALUES (16,"Admin Ruben");
INSERT INTO ENTRENADOR VALUES (17,"Admin Jose Manuel");
INSERT INTO ENTRENADOR VALUES (18,"Andres");
INSERT INTO ENTRENADOR VALUES (19,"Yessica");
INSERT INTO ENTRENADOR VALUES (20,"Danielle");
INSERT INTO ENTRENADOR VALUES (21,"Ruben");
INSERT INTO ENTRENADOR VALUES (22,"Ridel");
INSERT INTO ENTRENADOR VALUES (23,"Cristian");
INSERT INTO ENTRENADOR VALUES (24,"Alejandro");
INSERT INTO ENTRENADOR VALUES (25,"Gersan");
INSERT INTO ENTRENADOR VALUES (26,"Profesor Alejandro");
INSERT INTO ENTRENADOR VALUES (27,"Profesor Johatham");
INSERT INTO ENTRENADOR VALUES (28,"Profesor Oak");

/**
 * CAMPEON DE LA LIGA
*/

INSERT INTO CAMPEON_LIGA VALUES (1,"Johto");

/**
 * ALTO MANDO
*/

INSERT INTO ALTO_MANDO VALUES (2,"Hielo");
INSERT INTO ALTO_MANDO VALUES (3,"Lucha");
INSERT INTO ALTO_MANDO VALUES (4,"Veneno");
INSERT INTO ALTO_MANDO VALUES (5,"Dragon");

/**
 * LIDERES DE GIMNASIO
*/

INSERT INTO LIDER_GIMNASIO VALUES (6,1);
INSERT INTO LIDER_GIMNASIO VALUES (7,2);
INSERT INTO LIDER_GIMNASIO VALUES (8,3);
INSERT INTO LIDER_GIMNASIO VALUES (9,4);
INSERT INTO LIDER_GIMNASIO VALUES (10,5);
INSERT INTO LIDER_GIMNASIO VALUES (11,6);
INSERT INTO LIDER_GIMNASIO VALUES (12,7);
INSERT INTO LIDER_GIMNASIO VALUES (13,8);

/**
 * VILLANOS
*/

INSERT INTO VILLANO VALUES (13,"Dominar el universo usando a todos los Pokemon");
INSERT INTO VILLANO VALUES (14,"Conseguir pokemons para el Team Rocket");
INSERT INTO VILLANO VALUES (15,"Conseguir pokemons para el Team Rocket");

/**
 * ENTRENADORES CASUALES
*/

INSERT INTO ENTRENADOR_CASUAL VALUES (16,8);
INSERT INTO ENTRENADOR_CASUAL VALUES (17,8);
INSERT INTO ENTRENADOR_CASUAL VALUES (18,7);
INSERT INTO ENTRENADOR_CASUAL VALUES (19,5);
INSERT INTO ENTRENADOR_CASUAL VALUES (20,3);
INSERT INTO ENTRENADOR_CASUAL VALUES (21,7);
INSERT INTO ENTRENADOR_CASUAL VALUES (22,6);
INSERT INTO ENTRENADOR_CASUAL VALUES (23,6);
INSERT INTO ENTRENADOR_CASUAL VALUES (24,5);
INSERT INTO ENTRENADOR_CASUAL VALUES (25,5);
INSERT INTO ENTRENADOR_CASUAL VALUES (26,1);
INSERT INTO ENTRENADOR_CASUAL VALUES (27,1);
INSERT INTO ENTRENADOR_CASUAL VALUES (28,8);

/**
 * TIENE
*/

INSERT INTO TIENE VALUES (1,18,1); /* Azul */
INSERT INTO TIENE VALUES (1,65,1); 
INSERT INTO TIENE VALUES (1,112,1);
INSERT INTO TIENE VALUES (1,103,1);
INSERT INTO TIENE VALUES (1,130,1);
INSERT INTO TIENE VALUES (1,6,1);

INSERT INTO TIENE VALUES (2,87,1); /* Lorelei */
INSERT INTO TIENE VALUES (2,91,1);
INSERT INTO TIENE VALUES (2,80,1);
INSERT INTO TIENE VALUES (2,124,1);
INSERT INTO TIENE VALUES (2,131,1);

INSERT INTO TIENE VALUES (3,95,2); /* Bruno */
INSERT INTO TIENE VALUES (3,107,1);
INSERT INTO TIENE VALUES (3,106,1);
INSERT INTO TIENE VALUES (3,68,1);

INSERT INTO TIENE VALUES (4,94,2); /* Agatha */
INSERT INTO TIENE VALUES (4,42,1);
INSERT INTO TIENE VALUES (4,93,1);
INSERT INTO TIENE VALUES (4,24,1);

INSERT INTO TIENE VALUES (5,149,1); /* Lance */
INSERT INTO TIENE VALUES (5,148,2);
INSERT INTO TIENE VALUES (5,130,1);
INSERT INTO TIENE VALUES (5,142,1);

INSERT INTO TIENE VALUES (6,74,1); /* Brock */
INSERT INTO TIENE VALUES (6,95,1);

INSERT INTO TIENE VALUES (7,120,1); /* Mysty */
INSERT INTO TIENE VALUES (7,121,1);

INSERT INTO TIENE VALUES (8,100,1); /* Lt. Surge */
INSERT INTO TIENE VALUES (8,25,1);
INSERT INTO TIENE VALUES (8,26,1);

INSERT INTO TIENE VALUES (9,71,1); /* Erika */
INSERT INTO TIENE VALUES (9,114,1);
INSERT INTO TIENE VALUES (9,45,1);

INSERT INTO TIENE VALUES (10,109,2); /* Koga */
INSERT INTO TIENE VALUES (10,89,1);
INSERT INTO TIENE VALUES (10,110,1);

INSERT INTO TIENE VALUES (11,64,1); /* Sabrina */
INSERT INTO TIENE VALUES (11,49,1);
INSERT INTO TIENE VALUES (11,122,1);
INSERT INTO TIENE VALUES (11,65,1);

INSERT INTO TIENE VALUES (12,58,1); /* Blaine */
INSERT INTO TIENE VALUES (12,77,1);
INSERT INTO TIENE VALUES (12,78,1);
INSERT INTO TIENE VALUES (12,59,1);

INSERT INTO TIENE VALUES (13,111,2); /* Giovanni */
INSERT INTO TIENE VALUES (13,51,1);
INSERT INTO TIENE VALUES (13,34,1);
INSERT INTO TIENE VALUES (13,31,1);

INSERT INTO TIENE VALUES (14,24,2); /* Jessie */
INSERT INTO TIENE VALUES (14,110,1);
INSERT INTO TIENE VALUES (14,52,1);

INSERT INTO TIENE VALUES (15,24,2); /* James */
INSERT INTO TIENE VALUES (15,110,1);
INSERT INTO TIENE VALUES (15,52,1);

INSERT INTO TIENE VALUES (16,65,1); /* Admin Ruben */
INSERT INTO TIENE VALUES (17,,1); /* Admin Jose Manuel */
INSERT INTO TIENE VALUES (18,,1); /* Andres */
INSERT INTO TIENE VALUES (19,133,1); /* Yessica */
INSERT INTO TIENE VALUES (20,,1); /* Danielle */
INSERT INTO TIENE VALUES (21,,1); /* Ruben */
INSERT INTO TIENE VALUES (22,,1); /* Ridel */
INSERT INTO TIENE VALUES (23,,1); /* Cristian */
INSERT INTO TIENE VALUES (24,,1); /* Alejandro */
INSERT INTO TIENE VALUES (25,,1); /* Gersan */
INSERT INTO TIENE VALUES (26,6,1); /* Profesor Alejandro */
INSERT INTO TIENE VALUES (27,,1); /* Profesor Johatham */
INSERT INTO TIENE VALUES (28,133,1); /* Profesor Oak */

/**
 * Objetos
*/

INSERT INTO OBJETO VALUES (1,"Pokedex","Entregado",NULL);
INSERT INTO OBJETO VALUES (2,"Mapa","Entregado",NULL);
INSERT INTO OBJETO VALUES (3,"Bicicleta","Entregado",NULL);
INSERT INTO OBJETO VALUES (4,"Bono bici","Entregado",NULL);
INSERT INTO OBJETO VALUES (5,"Cania vieja","Entregado",NULL);
INSERT INTO OBJETO VALUES (6,"Cania buena","Entregado",NULL);
INSERT INTO OBJETO VALUES (7,"Supercania","Entregado",NULL);
INSERT INTO OBJETO VALUES (8,"Fosil domo","Entregado",500);
INSERT INTO OBJETO VALUES (9,"Fosil helix","Entregado",500);
INSERT INTO OBJETO VALUES (10,"Monedero","Entregado",NULL);
INSERT INTO OBJETO VALUES (11,"Pokeflauta","Entregado",NULL);
INSERT INTO OBJETO VALUES (12,"Poke Ball","Comprado",100);
INSERT INTO OBJETO VALUES (13,"Super Ball","Comprado",300);
INSERT INTO OBJETO VALUES (14,"Ultra Ball","Comprado",600);
INSERT INTO OBJETO VALUES (15,"Master Ball","Entregado",NULL);
INSERT INTO OBJETO VALUES (16,"Safari Ball","Comprado",NULL);
INSERT INTO OBJETO VALUES (17,"MO01 Corte","Entregado",NULL);
INSERT INTO OBJETO VALUES (18,"MO02 Vuelo","Recogido",NULL);
INSERT INTO OBJETO VALUES (19,"MO03 Surf","Recogido",NULL);
INSERT INTO OBJETO VALUES (20,"MO04 Fuerza","Entregado",NULL);
INSERT INTO OBJETO VALUES (21,"MO05 Destello","Entregado",NULL);
INSERT INTO OBJETO VALUES (22,"MT01 Megapunio","Comprado",NULL);
INSERT INTO OBJETO VALUES (23,"MT02 Viento Cortante","Comprado",NULL);
INSERT INTO OBJETO VALUES (24,"MT03 Danza Espada","Recogido",NULL);
INSERT INTO OBJETO VALUES (25,"MT04 Remolino","Recogido",NULL);
INSERT INTO OBJETO VALUES (26,"MT05 Megapatada","Comprado",NULL);
INSERT INTO OBJETO VALUES (27,"MT06 Toxico","Entregado",NULL);
INSERT INTO OBJETO VALUES (28,"MT07 Perforador","Comprado",NULL);
INSERT INTO OBJETO VALUES (29,"MT08 Golpe Cuerpo","Recodigo",NULL);
INSERT INTO OBJETO VALUES (30,"MT09 Derribo","Comprado",NULL);
INSERT INTO OBJETO VALUES (31,"MT10 Doble Filo","Recogido",NULL);
INSERT INTO OBJETO VALUES (32,"MT11 Rayo Bubuja","Entregado",NULL);
INSERT INTO OBJETO VALUES (33,"MT12 Pistola Agua","Recogido",NULL);
INSERT INTO OBJETO VALUES (34,"MT13 Rayo Hielo","Recogido",NULL);
INSERT INTO OBJETO VALUES (35,"MT14 Ventisca","Recogido",NULL);
INSERT INTO OBJETO VALUES (36,"MT15 Hiperrayo","Comprado",NULL);
INSERT INTO OBJETO VALUES (37,"MT16 Dia de pago","Recogido",NULL);
INSERT INTO OBJETO VALUES (38,"MT17 Sumision","Comprado",NULL);
INSERT INTO OBJETO VALUES (39,"MT18 Contraataque","Recogido",NULL);
INSERT INTO OBJETO VALUES (40,"MT19 Movimineto Sismico","Recogido",NULL);
INSERT INTO OBJETO VALUES (41,"MT20 Furia","Recogido",NULL);
INSERT INTO OBJETO VALUES (42,"MT21 Megaagotar","Entregado",NULL);
INSERT INTO OBJETO VALUES (43,"MT22 Rayo solar","Recogido",NULL);
INSERT INTO OBJETO VALUES (44,"MT23 Furia dragon","Comprado",NULL);
INSERT INTO OBJETO VALUES (45,"MT24 Rayo","Entregado",NULL);
INSERT INTO OBJETO VALUES (46,"MT25 Trueno","Recogido",NULL);
INSERT INTO OBJETO VALUES (47,"MT26 Terremoto","Recogido",NULL);
INSERT INTO OBJETO VALUES (48,"MT27 Fisura","Entregado",NULL);
INSERT INTO OBJETO VALUES (49,"MT28 Excavar","Recogido",NULL);
INSERT INTO OBJETO VALUES (50,"MT29 Psiquico","Recogido",NULL);
INSERT INTO OBJETO VALUES (51,"MT30 Teletransporte","Recogido",NULL);
INSERT INTO OBJETO VALUES (52,"MT31 Mimetico","Recogido",NULL);
INSERT INTO OBJETO VALUES (53,"MT32 Doble Equipo","Comprado",NULL);
INSERT INTO OBJETO VALUES (54,"MT33 Reflejo","Comprado",NULL);
INSERT INTO OBJETO VALUES (55,"MT34 Venganza","Entregado",NULL);
INSERT INTO OBJETO VALUES (56,"MT35 Metronomo","Recogido",NULL);
INSERT INTO OBJETO VALUES (57,"MT36 Autodestruccion","Recogido",NULL);
INSERT INTO OBJETO VALUES (58,"MT37 Bomba huevo","Comprado",NULL);
INSERT INTO OBJETO VALUES (59,"MT38 LLamarada","Entregado",NULL);
INSERT INTO OBJETO VALUES (60,"MT39 Rapidez","Recogido",NULL);
INSERT INTO OBJETO VALUES (61,"MT40 Cabezazo","Recogido",NULL);
INSERT INTO OBJETO VALUES (62,"MT41 Amortiguador","Recogido",NULL);
INSERT INTO OBJETO VALUES (63,"MT42 Come suenios","Recogido",NULL);
INSERT INTO OBJETO VALUES (64,"MT43 Ataque aereo","Recogido",NULL);
INSERT INTO OBJETO VALUES (65,"MT44 Descanso","Recogido",NULL);
INSERT INTO OBJETO VALUES (66,"MT45 Onda trueno","Recogido",NULL);
INSERT INTO OBJETO VALUES (67,"MT46 Psicoonda","Entregado",NULL);
INSERT INTO OBJETO VALUES (68,"MT47 Explosion","Recogido",NULL);
INSERT INTO OBJETO VALUES (69,"MT48 Avalancha","Recogido",NULL);
INSERT INTO OBJETO VALUES (70,"MT49 Triataque","Recogido",NULL);
INSERT INTO OBJETO VALUES (71,"MT50 Sustituto","Comprado",NULL);

/**
 * OBJETOS COMUNES
*/

INSERT INTO OBJETO_COMUN VALUES (1,"Muestra informacion sobre los pokemon");
INSERT INTO OBJETO_COMUN VALUES (2,"Muestra una imagen de la región en la que estas");
INSERT INTO OBJETO_COMUN VALUES (3,"Te permite desplazarte mas rapido");
INSERT INTO OBJETO_COMUN VALUES (4,"Te permite conseguir una bicicleta");
INSERT INTO OBJETO_COMUN VALUES (5,"Te permite pescar con dificultad");
INSERT INTO OBJETO_COMUN VALUES (6,"Te permite pescar con mas facilidad");
INSERT INTO OBJETO_COMUN VALUES (7,"Te permite pescar facilmente");
INSERT INTO OBJETO_COMUN VALUES (8,"Te permite conseguir a Kabuto");
INSERT INTO OBJETO_COMUN VALUES (9,"Te permite conseguir a Omanyte");
INSERT INTO OBJETO_COMUN VALUES (10,"Te permite guardar el dinero");
INSERT INTO OBJETO_COMUN VALUES (11,"Te permite despertar a Snorlax");

/**
 * POKE BALLS
*/

INSERT INTO POKEBALL VALUES (12,1);
INSERT INTO POKEBALL VALUES (13,1.5);
INSERT INTO POKEBALL VALUES (14,2);
INSERT INTO POKEBALL VALUES (15,255);
INSERT INTO POKEBALL VALUES (16,1.5);

/**
 * MAQUINAS
*/

INSERT INTO MAQUINA VALUES (17,);
INSERT INTO MAQUINA VALUES (18,);
INSERT INTO MAQUINA VALUES (19,);
INSERT INTO MAQUINA VALUES (20,);
INSERT INTO MAQUINA VALUES (21,);
INSERT INTO MAQUINA VALUES (22,);
INSERT INTO MAQUINA VALUES (23,);
INSERT INTO MAQUINA VALUES (24,);
INSERT INTO MAQUINA VALUES (25,);
INSERT INTO MAQUINA VALUES (26,);
INSERT INTO MAQUINA VALUES (27,);
INSERT INTO MAQUINA VALUES (28,);
INSERT INTO MAQUINA VALUES (29,);
INSERT INTO MAQUINA VALUES (30,);
INSERT INTO MAQUINA VALUES (31,);
INSERT INTO MAQUINA VALUES (32,);
INSERT INTO MAQUINA VALUES (33,);
INSERT INTO MAQUINA VALUES (34,);
INSERT INTO MAQUINA VALUES (35,);
INSERT INTO MAQUINA VALUES (36,);
INSERT INTO MAQUINA VALUES (37,);
INSERT INTO MAQUINA VALUES (38,);
INSERT INTO MAQUINA VALUES (39,);
INSERT INTO MAQUINA VALUES (40,);
INSERT INTO MAQUINA VALUES (41,);
INSERT INTO MAQUINA VALUES (42,);
INSERT INTO MAQUINA VALUES (43,);
INSERT INTO MAQUINA VALUES (44,);
INSERT INTO MAQUINA VALUES (45,);
INSERT INTO MAQUINA VALUES (46,);
INSERT INTO MAQUINA VALUES (47,);
INSERT INTO MAQUINA VALUES (48,);
INSERT INTO MAQUINA VALUES (49,);
INSERT INTO MAQUINA VALUES (50,);
INSERT INTO MAQUINA VALUES (51,);
INSERT INTO MAQUINA VALUES (52,);
INSERT INTO MAQUINA VALUES (53,);
INSERT INTO MAQUINA VALUES (54,);
INSERT INTO MAQUINA VALUES (55,);
INSERT INTO MAQUINA VALUES (56,);
INSERT INTO MAQUINA VALUES (57,);
INSERT INTO MAQUINA VALUES (58,);
INSERT INTO MAQUINA VALUES (59,);
INSERT INTO MAQUINA VALUES (60,);
INSERT INTO MAQUINA VALUES (61,);
INSERT INTO MAQUINA VALUES (62,);
INSERT INTO MAQUINA VALUES (63,);
INSERT INTO MAQUINA VALUES (64,);
INSERT INTO MAQUINA VALUES (65,);
INSERT INTO MAQUINA VALUES (66,);
INSERT INTO MAQUINA VALUES (67,);
INSERT INTO MAQUINA VALUES (68,);
INSERT INTO MAQUINA VALUES (69,);
INSERT INTO MAQUINA VALUES (70,);
INSERT INTO MAQUINA VALUES (71,);

/**
 * ENTRENADOR EQUIPA
*/

/**
 * POKEMON EQUIPA
*/