INSERT INTO ESTADO VALUES (1,'Paralizado',1,'Puede evitar que el pokemon ataque');
INSERT INTO ESTADO VALUES (2,'Quemado',1,'Dania al pokemon cada ronda');
INSERT INTO ESTADO VALUES (3,'Envenenado',1,'Dania al pokemon cada ronda exponencialmente');
INSERT INTO ESTADO VALUES (4,'Dormido',1,'Duerme al pokemon');
INSERT INTO ESTADO VALUES (5,'Congelado',1,'Puede evitar que el pokemon ataque');
INSERT INTO ESTADO VALUES (6,'Confuso',2,'Puede evitar que el pokemon ataque y que se haga danio');
INSERT INTO ESTADO VALUES (7,'Enamorado',2,'Puede evitar que el pokemon ataque');
INSERT INTO ESTADO VALUES (8,'Drenado',2,'Roba vida del pokemon y se la da al atacante');
INSERT INTO ESTADO VALUES (9,'Maldito',2,'Dania al pokemon');
INSERT INTO ESTADO VALUES (10,'Atrapado',2,'Evita que el pokemon huya');