INSERT INTO LIDER_GIMNASIO VALUES (6,1);
INSERT INTO LIDER_GIMNASIO VALUES (7,2);
INSERT INTO LIDER_GIMNASIO VALUES (8,3);
INSERT INTO LIDER_GIMNASIO VALUES (9,4);
INSERT INTO LIDER_GIMNASIO VALUES (10,5);
INSERT INTO LIDER_GIMNASIO VALUES (11,6);
INSERT INTO LIDER_GIMNASIO VALUES (12,7);
INSERT INTO LIDER_GIMNASIO VALUES (13,8);