INSERT INTO OBJETO VALUES (1,'Pokedex','Entregado');
INSERT INTO OBJETO VALUES (2,'Mapa','Entregado');
INSERT INTO OBJETO VALUES (3,'Bicicleta','Entregado');
INSERT INTO OBJETO VALUES (4,'Bono bici','Entregado');
INSERT INTO OBJETO VALUES (5,'Cania vieja','Entregado');
INSERT INTO OBJETO VALUES (6,'Cania buena','Entregado');
INSERT INTO OBJETO VALUES (7,'Supercania','Entregado');
INSERT INTO OBJETO VALUES (8,'Fosil domo','Entregado');
INSERT INTO OBJETO VALUES (9,'Fosil helix','Entregado');
INSERT INTO OBJETO VALUES (10,'Monedero','Entregado');
INSERT INTO OBJETO VALUES (11,'Pokeflauta','Entregado');
INSERT INTO OBJETO VALUES (12,'Poke Ball','Comprado');
INSERT INTO OBJETO VALUES (13,'Super Ball','Comprado');
INSERT INTO OBJETO VALUES (14,'Ultra Ball','Comprado');
INSERT INTO OBJETO VALUES (15,'Master Ball','Entregado');
INSERT INTO OBJETO VALUES (16,'Safari Ball','Comprado');
INSERT INTO OBJETO VALUES (17,'MO01 Corte','Entregado');
INSERT INTO OBJETO VALUES (18,'MO02 Vuelo','Recogido');
INSERT INTO OBJETO VALUES (19,'MO03 Surf','Recogido');
INSERT INTO OBJETO VALUES (20,'MO04 Fuerza','Entregado');
INSERT INTO OBJETO VALUES (21,'MO05 Destello','Entregado');
INSERT INTO OBJETO VALUES (22,'MT01 Megapunio','Comprado');
INSERT INTO OBJETO VALUES (23,'MT02 Viento Cortante','Comprado');
INSERT INTO OBJETO VALUES (24,'MT03 Danza Espada','Recogido');
INSERT INTO OBJETO VALUES (25,'MT04 Remolino','Recogido');
INSERT INTO OBJETO VALUES (26,'MT05 Megapatada','Comprado');
INSERT INTO OBJETO VALUES (27,'MT06 Toxico','Entregado');
INSERT INTO OBJETO VALUES (28,'MT07 Perforador','Comprado');
INSERT INTO OBJETO VALUES (29,'MT08 Golpe Cuerpo','Recogido');
INSERT INTO OBJETO VALUES (30,'MT09 Derribo','Comprado');
INSERT INTO OBJETO VALUES (31,'MT10 Doble Filo','Recogido');
INSERT INTO OBJETO VALUES (32,'MT11 Rayo Burbuja','Entregado');
INSERT INTO OBJETO VALUES (33,'MT12 Pistola Agua','Recogido');
INSERT INTO OBJETO VALUES (34,'MT13 Rayo Hielo','Recogido');
INSERT INTO OBJETO VALUES (35,'MT14 Ventisca','Recogido');
INSERT INTO OBJETO VALUES (36,'MT15 Hiperrayo','Comprado');
INSERT INTO OBJETO VALUES (37,'MT16 Dia de pago','Recogido');
INSERT INTO OBJETO VALUES (38,'MT17 Sumision','Comprado');
INSERT INTO OBJETO VALUES (39,'MT18 Contraataque','Recogido');
INSERT INTO OBJETO VALUES (40,'MT19 Movimineto Sismico','Recogido');
INSERT INTO OBJETO VALUES (41,'MT20 Furia','Recogido');
INSERT INTO OBJETO VALUES (42,'MT21 Megaagotar','Entregado');
INSERT INTO OBJETO VALUES (43,'MT22 Rayo solar','Recogido');
INSERT INTO OBJETO VALUES (44,'MT23 Furia dragon','Comprado');
INSERT INTO OBJETO VALUES (45,'MT24 Rayo','Entregado');
INSERT INTO OBJETO VALUES (46,'MT25 Trueno','Recogido');
INSERT INTO OBJETO VALUES (47,'MT26 Terremoto','Recogido');
INSERT INTO OBJETO VALUES (48,'MT27 Fisura','Entregado');
INSERT INTO OBJETO VALUES (49,'MT28 Excavar','Recogido');
INSERT INTO OBJETO VALUES (50,'MT29 Psiquico','Recogido');
INSERT INTO OBJETO VALUES (51,'MT30 Teletransporte','Recogido');
INSERT INTO OBJETO VALUES (52,'MT31 Mimetico','Recogido');
INSERT INTO OBJETO VALUES (53,'MT32 Doble Equipo','Comprado');
INSERT INTO OBJETO VALUES (54,'MT33 Reflejo','Comprado');
INSERT INTO OBJETO VALUES (55,'MT34 Venganza','Entregado');
INSERT INTO OBJETO VALUES (56,'MT35 Metronomo','Recogido');
INSERT INTO OBJETO VALUES (57,'MT36 Autodestruccion','Recogido');
INSERT INTO OBJETO VALUES (58,'MT37 Bomba huevo','Comprado');
INSERT INTO OBJETO VALUES (59,'MT38 LLamarada','Entregado');
INSERT INTO OBJETO VALUES (60,'MT39 Rapidez','Recogido');
INSERT INTO OBJETO VALUES (61,'MT40 Cabezazo','Recogido');
INSERT INTO OBJETO VALUES (62,'MT41 Amortiguador','Recogido');
INSERT INTO OBJETO VALUES (63,'MT42 Come suenios','Recogido');
INSERT INTO OBJETO VALUES (64,'MT43 Ataque aereo','Recogido');
INSERT INTO OBJETO VALUES (65,'MT44 Descanso','Recogido');
INSERT INTO OBJETO VALUES (66,'MT45 Onda trueno','Recogido');
INSERT INTO OBJETO VALUES (67,'MT46 Psicoonda','Entregado');
INSERT INTO OBJETO VALUES (68,'MT47 Explosion','Recogido');
INSERT INTO OBJETO VALUES (69,'MT48 Avalancha','Recogido');
INSERT INTO OBJETO VALUES (70,'MT49 Triataque','Recogido');
INSERT INTO OBJETO VALUES (71,'MT50 Sustituto','Comprado');