INSERT INTO POKEMON_EQUIPA VALUES (143,11);
INSERT INTO POKEMON_EQUIPA VALUES (138,8);
INSERT INTO POKEMON_EQUIPA VALUES (140,9);
INSERT INTO POKEMON_EQUIPA VALUES (52,10);
INSERT INTO POKEMON_EQUIPA VALUES (130,6);